# Generated by Codex on 2026-07-03

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_phoneotpchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenceproof",
            name="blurred_preview_file",
            field=models.FileField(blank=True, storage=apps.accounts.storage.PrivateMediaStorage(), upload_to="residence-proofs/previews/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="residenceproof",
            name="file",
            field=models.FileField(storage=apps.accounts.storage.PrivateMediaStorage(), upload_to="residence-proofs/%Y/%m/"),
        ),
    ]
