# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_private_residence_proof_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotpchallenge",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveIndex(
            model_name="phoneotpchallenge",
            name="accounts_ph_phone_n_0fd1c2_idx",
        ),
        migrations.AddIndex(
            model_name="phoneotpchallenge",
            index=models.Index(fields=["phone_number", "verified_at", "consumed_at"], name="accounts_ph_phone_n_025c54_idx"),
        ),
    ]
