# Generated by Codex on 2026-07-03

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phoneotpchallenge_consumed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="residenceproof",
            name="blurred_preview_file",
            field=models.FileField(
                blank=True,
                storage=apps.accounts.storage.PublicMediaStorage(),
                upload_to="previews/residence-proofs/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="residenceproof",
            name="file",
            field=models.FileField(
                storage=apps.accounts.storage.PrivateMediaStorage(),
                upload_to="raw/residence-proofs/%Y/%m/",
            ),
        ),
    ]
