# Generated by Django 5.2.15 on 2026-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
