# Generated by Django 5.2.15 on 2026-07-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_gender_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_alerts', models.BooleanField(default=True)),
                ('report_updates', models.BooleanField(default=True)),
                ('community_sharing', models.BooleanField(default=False)),
                ('location_confirmation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
