# Generated by Django 5.2.15 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_residentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='residenceproof',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
