# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_residenceproof_phash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="responder_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tanod", "Barangay Tanod"),
                    ("bhw", "Barangay Health Worker"),
                    ("bdrrmo", "BDRRMO"),
                    ("other", "Other Responder"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_on_duty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="current_latitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_longitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
