# Generated by Django 5.2.15 on 2026-07-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_responder_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentsettings',
            name='sos_placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('inline', 'Inline'), ('compact', 'Compact')], default='sidebar', max_length=16),
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deletion', 'Deletion'), ('data_export', 'Data Export')], max_length=24)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('staff_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_account_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
