# Generated by Claude Code

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_residentsettings_sos_placement_accountrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="residenceproof",
            name="phash_blocks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
