# Generated by Django 5.2.15 on 2026-07-12 06:59

import apps.accounts.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_residenceproof_phash_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.SlugField(default='paddleocr', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unavailable', 'Unavailable')], default='not_configured', max_length=24)),
                ('circuit_state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('half_open', 'Half-open')], default='closed', max_length=16)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'OCR service statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='verificationcheck',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='residenceproof',
            name='side',
            field=models.CharField(choices=[('single', 'Single page'), ('front', 'Front'), ('back', 'Back'), ('other', 'Other')], default='single', max_length=16),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='failure_reason_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='provider_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='retryable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='rule_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='trigger',
            field=models.CharField(choices=[('registration', 'Registration'), ('retry', 'Retry'), ('recovery', 'Service recovery'), ('official', 'Official request'), ('system', 'System')], default='registration', max_length=24),
        ),
        migrations.AlterField(
            model_name='verificationcheck',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('passed', 'Passed'), ('manual_review', 'Manual review'), ('failed', 'Failed'), ('error', 'Service error'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='OCRConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='residence_proof', max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='accounts.ocrconfigurationversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ocr_configurations', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_ocr_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='accounts.ocrconfigurationversion'),
        ),
        migrations.CreateModel(
            name='OCRDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('identity', 'Identity document'), ('certificate', 'Certificate'), ('utility', 'Utility bill'), ('agreement', 'Agreement'), ('financial', 'Financial statement'), ('property', 'Property record'), ('other', 'Other')], default='other', max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('requires_front', models.BooleanField(default=False)),
                ('requires_back', models.BooleanField(default=False)),
                ('allowed_sides', models.JSONField(blank=True, default=list)),
                ('accepted_mime_types', models.JSONField(blank=True, default=list)),
                ('max_files', models.PositiveSmallIntegerField(default=1)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('provider_names', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='accounts.ocrconfigurationversion')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='residenceproof',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='accounts.ocrdocumenttype'),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='accounts.ocrdocumenttype'),
        ),
        migrations.CreateModel(
            name='OCRFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('name', 'Person name'), ('address', 'Address'), ('date', 'Date'), ('identifier', 'Identifier'), ('number', 'Number')], default='text', max_length=24)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('sides', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('extraction_hints', models.JSONField(blank=True, default=dict)),
                ('normalization', models.CharField(choices=[('none', 'None'), ('uppercase', 'Uppercase'), ('name', 'Person name'), ('address', 'Address'), ('date', 'Date'), ('digits', 'Digits only'), ('alphanumeric', 'Alphanumeric')], default='none', max_length=24)),
                ('format', models.CharField(choices=[('none', 'No fixed format'), ('text', 'Text'), ('date_mdy', 'Date (MM/DD/YYYY)'), ('date_ymd', 'Date (YYYY-MM-DD)'), ('alphanumeric', 'Alphanumeric'), ('numeric', 'Numeric')], default='none', max_length=24)),
                ('min_confidence', models.DecimalField(decimal_places=3, default=0.8, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.ocrdocumenttype')),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='OCRRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('rule_type', models.CharField(choices=[('required', 'Required field'), ('profile_match', 'Resident profile match'), ('similarity', 'Similarity threshold'), ('recency', 'Document recency'), ('allowed_value', 'Allowed value'), ('contains_keyword', 'Contains keyword'), ('format', 'Format'), ('not_expired', 'Not expired'), ('image_quality', 'Image quality')], max_length=32)),
                ('operator', models.CharField(choices=[('exists', 'Exists'), ('matches_profile', 'Matches resident profile'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('equals', 'Equals'), ('one_of', 'One of'), ('contains_any', 'Contains any'), ('within_days', 'Within days'), ('not_expired', 'Not expired')], max_length=32)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('on_failure', models.CharField(choices=[('manual_review', 'Send to manual review'), ('warning', 'Record warning')], default='manual_review', max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.ocrconfigurationversion')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.ocrdocumenttype')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='accounts.ocrfielddefinition')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OCRSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('file', models.FileField(blank=True, storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='raw/ocr-samples/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ocr_samples', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='accounts.ocrdocumenttype')),
            ],
            options={
                'ordering': ['document_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OCRTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='raw/ocr-tests/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed'), ('error', 'Service error'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('provider_job_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('extracted_fields', models.JSONField(blank=True, default=dict)),
                ('rule_results', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='accounts.ocrconfigurationversion')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='accounts.ocrdocumenttype')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ocr_test_runs', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='accounts.ocrsample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceVerificationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_email', 'Awaiting email verification'), ('queued', 'Queued'), ('processing', 'Processing'), ('manual_review', 'Manual review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_email', max_length=24)),
                ('review_reason', models.CharField(blank=True, choices=[('ocr_unavailable', 'OCR unavailable'), ('low_confidence', 'Low OCR confidence'), ('missing_required_field', 'Missing required field'), ('document_type_mismatch', 'Document type mismatch'), ('rule_mismatch', 'Validation rule mismatch'), ('official_requested', 'Official requested review'), ('legacy_pending', 'Legacy pending verification')], max_length=40)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('retry_eligible', models.BooleanField(default=True)),
                ('decision_source', models.CharField(choices=[('none', 'No decision'), ('system', 'System'), ('official', 'Barangay official')], default='none', max_length=16)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.ocrconfigurationversion')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_residence_verification_cases', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.ocrdocumenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_verification_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='residenceproof',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='accounts.residenceverificationcase'),
        ),
        migrations.AddField(
            model_name='verificationcheck',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='accounts.residenceverificationcase'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['status', 'available_at'], name='accounts_ocr_attempt_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['case', '-created_at'], name='accounts_ocr_attempt_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationcheck',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('case', 'proof', 'attempt_number'), name='accounts_ocr_attempt_case_proof_no_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verificationcheck',
            constraint=models.CheckConstraint(condition=models.Q(('ocr_confidence__isnull', True), models.Q(('ocr_confidence__gte', 0), ('ocr_confidence__lte', 1)), _connector='OR'), name='accounts_ocr_attempt_conf_range'),
        ),
        migrations.AddIndex(
            model_name='ocrconfigurationversion',
            index=models.Index(fields=['scope', 'status'], name='acct_ocr_cfg_scope_status'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(fields=('scope', 'version'), name='accounts_ocr_cfg_scope_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('scope',), name='accounts_ocr_cfg_one_draft_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('scope',), name='accounts_ocr_cfg_one_published_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='accounts_ocr_cfg_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='accounts_ocr_cfg_revision_gte_1'),
        ),
        migrations.AddIndex(
            model_name='ocrdocumenttype',
            index=models.Index(fields=['configuration', 'enabled', 'display_order'], name='acct_ocr_doc_cfg_enabled'),
        ),
        migrations.AddConstraint(
            model_name='ocrdocumenttype',
            constraint=models.UniqueConstraint(fields=('configuration', 'code'), name='accounts_ocr_doc_config_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ocrdocumenttype',
            constraint=models.CheckConstraint(condition=models.Q(('max_files__gte', 1)), name='accounts_ocr_doc_max_files_gte_1'),
        ),
        migrations.AddIndex(
            model_name='ocrfielddefinition',
            index=models.Index(fields=['document_type', 'enabled', 'display_order'], name='acct_ocr_field_doc_enabled'),
        ),
        migrations.AddConstraint(
            model_name='ocrfielddefinition',
            constraint=models.UniqueConstraint(fields=('document_type', 'code'), name='accounts_ocr_field_doc_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ocrfielddefinition',
            constraint=models.CheckConstraint(condition=models.Q(('min_confidence__gte', 0), ('min_confidence__lte', 1)), name='accounts_ocr_field_conf_range'),
        ),
        migrations.AddIndex(
            model_name='ocrrule',
            index=models.Index(fields=['configuration', 'document_type', 'enabled'], name='accounts_ocr_rule_cfg_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrrule',
            constraint=models.UniqueConstraint(fields=('configuration', 'code'), name='accounts_ocr_rule_config_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ocrrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__isnull', True), models.Q(('threshold__gte', 0), ('threshold__lte', 1)), _connector='OR'), name='accounts_ocr_rule_threshold_range'),
        ),
        migrations.AddIndex(
            model_name='ocrtestrun',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ocr_test_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrtestrun',
            index=models.Index(fields=['requested_by', '-created_at'], name='acct_ocr_test_requester'),
        ),
        migrations.AddConstraint(
            model_name='ocrtestrun',
            constraint=models.CheckConstraint(condition=models.Q(('ocr_confidence__isnull', True), models.Q(('ocr_confidence__gte', 0), ('ocr_confidence__lte', 1)), _connector='OR'), name='accounts_ocr_test_conf_range'),
        ),
        migrations.AddIndex(
            model_name='residenceverificationcase',
            index=models.Index(fields=['status', '-priority', 'created_at'], name='accounts_res_case_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='residenceverificationcase',
            index=models.Index(fields=['retry_eligible', 'status', 'updated_at'], name='accounts_res_case_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='residenceverificationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_email', 'queued', 'processing', 'manual_review'])), fields=('user',), name='accounts_one_active_res_case'),
        ),
        migrations.AddConstraint(
            model_name='residenceverificationcase',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='accounts_res_case_revision_gte_1'),
        ),
    ]
