# Generated by Django 5.2.15 on 2026-07-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_emailotpchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("deletion", "Deletion"),
                    ("data_export", "Data Export"),
                    ("deactivation", "Deactivation"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="residentprofile",
            name="barangay",
            field=models.CharField(default="Marikina Heights", max_length=120),
        ),
    ]
