# Generated by Django 5.2.15 on 2026-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_accountrequest_type_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status', 'is_on_duty', 'responder_unit'], name='accounts_resp_avail'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='accounts_resp_coords'),
        ),
    ]
