# Generated by Django 5.2.15 on 2026-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_identityidentifierclaim_and_duplicate_review_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='responder_unit',
            field=models.CharField(blank=True, choices=[('tanod', 'Barangay Tanod'), ('bhw', 'Barangay Health Worker'), ('bdrrmo', 'BDRRMO')], max_length=24),
        ),
    ]
