# Generated by Django 5.2.15 on 2026-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_backfill_pending_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtestrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
