# Generated by Django 5.2.15 on 2026-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_ocr_space_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrservicestatus',
            name='provider',
            field=models.SlugField(default='ocrspace', max_length=64, unique=True),
        ),
    ]
