# Generated by Django 5.2.15 on 2026-08-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_auditlog_options_auditlog_audit_log_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_asn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_org',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_verdict',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.CreateModel(
            name='VerificationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_overrides', to=settings.AUTH_USER_MODEL)),
                ('verification_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='accounts.verificationcheck')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
