# Generated by Django 5.2.15 on 2026-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_residentprofile_profile_completed_at_user_ip_asn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealthDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('module_key', models.SlugField(max_length=40)),
                ('severity', models.PositiveSmallIntegerField(default=0)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['module_key', 'day'], name='accounts_se_module__da26df_idx')],
                'unique_together': {('day', 'module_key')},
            },
        ),
    ]
