# Generated by Django 5.2.15 on 2026-08-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_user_supabase_user_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='residenceproof',
            name='accounts_re_sha256__bb2d13_idx',
        ),
    ]
