# Generated by Django 5.2.15 on 2026-08-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_remove_residenceproof_accounts_re_sha256__bb2d13_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPhashBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('object_id', models.BigIntegerField()),
                ('kind', models.CharField(max_length=5)),
                ('band_index', models.PositiveSmallIntegerField()),
                ('band_value', models.CharField(max_length=4)),
                ('source_created_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'kind', 'band_index', 'band_value'], name='mediaphash_lookup'), models.Index(fields=['scope', 'object_id'], name='mediaphash_owner')],
            },
        ),
    ]
