# Generated by Django 5.2.17 on 2026-08-23 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_datasubjectrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_hash', models.CharField(db_index=True, max_length=64)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(max_length=16)),
                ('boundary_revision', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ocrconfigurationversion',
            name='accounts_ocr_cfg_scope_version_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='ocrconfigurationversion',
            name='accounts_ocr_cfg_one_draft_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='ocrconfigurationversion',
            name='accounts_ocr_cfg_one_published_per_scope',
        ),
        migrations.RemoveIndex(
            model_name='ocrconfigurationversion',
            name='acct_ocr_cfg_scope_status',
        ),
    ]
