# Generated by Django 5.2.17 on 2026-08-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_communityresolution_and_more'),
        ('emergencies', '0041_backuprequest_community_emergencyassignmentroute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrconfigurationversion',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_configurations', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='residenceverificationcase',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residence_verification_cases', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='home_accuracy_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='home_location_source',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='ocrconfigurationversion',
            index=models.Index(fields=['community', 'scope', 'status'], name='acct_ocr_cfg_comm_status'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(fields=('community', 'scope', 'version'), name='accounts_ocr_cfg_comm_scope_ver_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('community', 'scope'), name='accounts_ocr_cfg_one_draft_per_comm'),
        ),
        migrations.AddConstraint(
            model_name='ocrconfigurationversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('community', 'scope'), name='accounts_ocr_cfg_one_pub_per_comm'),
        ),
        migrations.AddField(
            model_name='communityresolution',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_resolutions', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='communityresolution',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signup_resolutions', to='accounts.ocrconfigurationversion'),
        ),
        migrations.AddIndex(
            model_name='communityresolution',
            index=models.Index(fields=['community', 'expires_at'], name='accounts_comm_res_expiry'),
        ),
    ]
