# Generated by Django 5.2.17 on 2026-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_ocrconfigurationversion_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residenceverificationcase',
            name='review_reason',
            field=models.CharField(blank=True, choices=[('ocr_unavailable', 'OCR unavailable'), ('low_confidence', 'Low OCR confidence'), ('missing_required_field', 'Missing required field'), ('document_type_mismatch', 'Document type mismatch'), ('rule_mismatch', 'Validation rule mismatch'), ('duplicate_identity', 'Possible duplicate identity'), ('media_integrity', 'Document did not look genuine'), ('resubmission_required', 'Request a new submission'), ('official_requested', 'Official requested review'), ('legacy_pending', 'Legacy pending verification')], max_length=40),
        ),
    ]
