# Generated by Django 5.2.17 on 2026-08-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_residenceverificationcase_review_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityresolution',
            name='email_challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_resolutions', to='accounts.emailotpchallenge'),
        ),
    ]
