# Generated by Django 5.2.17 on 2026-08-29 13:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_audit_community(apps, schema_editor):
    AuditLog = apps.get_model("accounts", "AuditLog")
    for row in AuditLog.objects.filter(community__isnull=True).iterator():
        user = row.target_user or row.actor
        if user is None:
            continue
        profile = getattr(user, "resident_profile", None)
        community_id = getattr(profile, "community_id", None)
        if community_id is None:
            community_id = user.designations.filter(is_active=True).values_list(
                "department__community_id", flat=True
            ).first()
        if community_id:
            AuditLog.objects.filter(pk=row.pk).update(community_id=community_id)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_residentsettings_location_sharing_enabled'),
        ('emergencies', '0049_community_psgc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='emergencies.community'),
        ),
        migrations.RunPython(backfill_audit_community, migrations.RunPython.noop),
    ]
