# Generated by Django 5.2.17 on 2026-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_auditlog_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_community_id',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_log_action',
        ),
    ]
