# Generated by Django 5.2.15 on 2026-08-01 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergencies', '0026_emergencyalert_category_needs_confirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(blank=True, db_index=True, max_length=24)),
                ('sender_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('body', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('gateway_message_id', models.CharField(blank=True, max_length=120)),
                ('gateway_received_at', models.DateTimeField(blank=True, help_text='Timestamp claimed by the gateway. Informational only unless validated.', null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Official submission time for anything created from this message.')),
                ('sender_match_status', models.CharField(blank=True, max_length=24)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('emergency_created', 'Emergency created'), ('command_handled', 'Command handled'), ('unrecognised', 'Unrecognised'), ('duplicate', 'Duplicate'), ('dropped_otp', 'Dropped (OTP-shaped)'), ('rejected', 'Rejected'), ('error', 'Error')], default='pending', max_length=32)),
                ('command_keyword', models.CharField(blank=True, max_length=24)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_sms_messages', to='emergencies.emergencyalert')),
                ('matched_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-server_received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_hash', models.CharField(db_index=True, max_length=64)),
                ('destination_last_four', models.CharField(blank=True, max_length=4)),
                ('body', models.TextField(blank=True, help_text='Blank for OTP purposes — codes are never persisted.')),
                ('segments', models.PositiveSmallIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('emergency', 'Emergency'), ('emergency_ack', 'Emergency acknowledgement'), ('dispatch', 'Responder dispatch'), ('command_reply', 'Command reply'), ('otp', 'Registration OTP'), ('official_alert', 'Official alert'), ('system', 'System')], default='system', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped (gateway disabled)')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('driver', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_sms_messages', to='emergencies.emergencyalert')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='sms.inboundsmsmessage')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inboundsmsmessage',
            index=models.Index(fields=['outcome', 'server_received_at'], name='sms_inbound_outcome_time'),
        ),
        migrations.AddIndex(
            model_name='inboundsmsmessage',
            index=models.Index(fields=['sender_hash', 'server_received_at'], name='sms_inbound_sender_time'),
        ),
        migrations.AddIndex(
            model_name='outboundsmsmessage',
            index=models.Index(fields=['status', 'created_at'], name='sms_outbound_status_time'),
        ),
        migrations.AddIndex(
            model_name='outboundsmsmessage',
            index=models.Index(fields=['purpose', 'created_at'], name='sms_outbound_purpose_time'),
        ),
    ]
