# Generated by Django 5.2.15 on 2026-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsoperatorpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundsmsmessage',
            name='idempotency_key',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
