# Generated by Django 5.2.15 on 2026-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_outboundsmsmessage_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundsmsmessage',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='outboundsmsmessage',
            name='provider_state',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
