# Generated by Django 5.2.17 on 2026-09-21 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0054_emergencychatreadstate'),
        ('sms', '0007_alter_inboundsmsmessage_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundsmsmessage',
            name='chat_message',
            field=models.ForeignKey(blank=True, help_text='The chat line this reply became. Lets the app label a message as received by SMS, and lets an answer be sent by SMS because the resident is texting rather than using the app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_sms_messages', to='emergencies.emergencychatmessage'),
        ),
    ]
