/**
 * All cities and municipalities in the Philippines, grouped by region.
 * Source: Philippine Statistics Authority (PSA) PSGC 2024.
 */

export const PHILIPPINE_CITIES = [
  // NCR (National Capital Region)
  "Caloocan",
  "Las Piñas",
  "Makati",
  "Malabon",
  "Mandaluyong",
  "Manila",
  "Marikina",
  "Muntinlupa",
  "Navotas",
  "Parañaque",
  "Pasay",
  "Pasig",
  "Pateros",
  "Quezon City",
  "San Juan",
  "Taguig",
  "Valenzuela",

  // Ilocos Region (Region I)
  "Alaminos",
  "Batac",
  "Candon",
  "Laoag",
  "San Carlos",
  "San Fernando",
  "Urdaneta",
  "Vigan",

  // Cagayan Valley (Region II)
  "Cauayan",
  "Ilagan",
  "Santiago",
  "Tuguegarao",

  // Central Luzon (Region III",
  "Angeles",
  "Balanga",
  "Cabanatuan",
  "Cabanatuan",
  "Gapan",
  "Mabalacat",
  "Malolos",
  "Meycauayan",
  "Olongapo",
  "Palayan",
  "San Fernando",
  "San Jose",
  "San Miguel",
  "Tarlac City",
  "Trece Martires",

  // Calabarzon (Region IV-A)",
  "Antipolo",
  "Bacoor",
  "Batangas City",
  "Biñan",
  "Cabuyao",
  "Calamba",
  "Cavite City",
  "Dasmarinas",
  "General Trias",
  "Imus",
  "Lipa",
  "Lucena",
  "San Pablo",
  "San Pedro",
  "Santa Rosa",
  "Tagaytay",
  "Talisay",
  "Tanauan",
  "Trece Martires",

  // Mimaropa (Region IV-B)
  "Calapan",
  "Puerto Princesa",

  // Bicol Region (Region V)
  "Iriga",
  "Legazpi",
  "Ligao",
  "Naga",
  "Tabaco",

  // Western Visayas (Region VI)
  "Bago",
  "Bacolod",
  "Cadiz",
  "Escalante",
  "Himamaylan",
  "Kabankalan",
  "La Carlota",
  "Sagay",
  "San Carlos",
  "Silay",
  "Talisay",
  "Victorias",

  // Central Visayas (Region VII)
  "Bogo",
  "Carcar",
  "Cebu City",
  "Danao",
  "Lapu-Lapu",
  "Mandaue",
  "Naga",
  "Talisay",
  "Toledo",

  // Eastern Visayas (Region VIII)
  "Borongan",
  "Calbayog",
  "Catbalogan",
  "Maasin",
  "Ormoc",
  "Tacloban",

  // Zamboanga Peninsula (Region IX)
  "Dapitan",
  "Dipolog",
  "Isabela",
  "Pagadian",
  "Zamboanga City",

  // Northern Mindanao (Region X)
  "Cagayan de Oro",
  "El Salvador",
  "Gingoog",
  "Iligan",
  "Oroquieta",
  "Ozamiz",
  "Tangub",

  // Davao Region (Region XI)
  "Davao City",
  "Digos",
  "Mati",
  "Panabo",
  "Samal",
  "Tagum",

  // Soccsksargen (Region XII)
  "Cotabato City",
  "General Santos",
  "Koronadal",
  "Tacurong",

  // Caraga (Region XIII)
  "Bayugan",
  "Bislig",
  "Butuan",
  "Cabadbaran",
  "Surigao",
  "Tandag",

  // Bangsamoro Autonomous Region in Muslim Mindanao (BARMM)
  "Cotabato City",
  "Marawi",
  "Lamitan",

  // Cordillera Administrative Region (CAR)
  "Baguio",
  "La Trinidad",

  // Highy Urbanized Cities (HUCs) - some already listed above
  "Puerto Princesa",
  "Olongapo",
  "Angeles",
  "San Fernando",
  "Antipolo",
  "Lucena",
  "Batangas City",
  "Lipa",
  "Trece Martires",
  "Calamba",
  "Bacoor",
  "Imus",
  "Dasmarinas",
  "San Pedro",
  "Biñan",
  "Cabuyao",
  "Santa Rosa",
  "General Trias",
  "Talisay",
  "Tanauan",
  "Bago",
  "Bacolod",
  "Iloilo City",
  "Passi",
  "Roxas",
  "Silay",
  "Talisay",
  "Victorias",
  "Kabankalan",
  "La Carlota",
  "Cadiz",
  "Sagay",
  "San Carlos",
  "Escalante",
  "Himamaylan",
  "Bogo",
  "Carcar",
  "Cebu City",
  "Danao",
  "Lapu-Lapu",
  "Mandaue",
  "Naga",
  "Toledo",
  "Borongan",
  "Calbayog",
  "Catbalogan",
  "Maasin",
  "Ormoc",
  "Tacloban",
  "Dapitan",
  "Dipolog",
  "Isabela",
  "Pagadian",
  "Zamboanga City",
  "Cagayan de Oro",
  "El Salvador",
  "Gingoog",
  "Iligan",
  "Oroquieta",
  "Ozamiz",
  "Tangub",
  "Davao City",
  "Digos",
  "Mati",
  "Panabo",
  "Samal",
  "Tagum",
  "Cotabato City",
  "General Santos",
  "Koronadal",
  "Tacurong",
  "Bayugan",
  "Bislig",
  "Butuan",
  "Cabadbaran",
  "Surigao",
  "Tandag",
  "Marawi",
  "Lamitan",
  "Baguio",
  "La Trinidad",
].filter((v, i, a) => a.indexOf(v) === i) // deduplicate
  .sort((a, b) => a.localeCompare(b))
