"""
Django settings for the E-Boses API backend.

Generated by django-admin startproject as a starting point.
"""

from datetime import timedelta
import os
from pathlib import Path
import socket
import sys
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import environ
from django.core.exceptions import ImproperlyConfigured

env = environ.Env()

BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file at the repo root
environ.Env.read_env(BASE_DIR.parent.parent / ".env")

# Environments are explicit: nothing counts as "local" just because a variable
# is unset. Local development opts in with DJANGO_ENV=local; any other value
# (or a missing value) gets production-safe, fail-closed behaviour below.
ENVIRONMENT = env("DJANGO_ENV", default="production")
IS_LOCAL_DEVELOPMENT = ENVIRONMENT == "local"

# Fail closed: never sign JWTs, refresh tokens, password-reset links or
# WebSocket tickets with the published dev placeholder outside local dev.
SECRET_KEY = env("DJANGO_SECRET_KEY", default="")
if not SECRET_KEY:
    if IS_LOCAL_DEVELOPMENT:
        SECRET_KEY = "local-development-only-secret-key"
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set (and safe to use) outside local development."
        )

DEBUG = env.bool("DEBUG", default=True)

# ALLOWED_HOSTS: pinned everywhere but local development. A staging/production
# deployment that forgets it fails at boot instead of accepting any Host.
if IS_LOCAL_DEVELOPMENT:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])
else:
    ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS must list the exact hostnames outside local development."
        )

# Application definition
ENABLE_GIS = env.bool("ENABLE_GIS", default=False)

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

if ENABLE_GIS:
    DJANGO_APPS.append("django.contrib.gis")

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "channels",
]

LOCAL_APPS = [
    "apps.accounts",
    "apps.assistant.apps.AssistantConfig",
    "apps.concerns",
    "apps.emergencies.apps.EmergenciesConfig",
    "apps.notifications",
    "apps.sms.apps.SmsConfig",
]

INSTALLED_APPS = ["daphne"] + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

IS_TEST_RUN = "test" in sys.argv
# Reverse geocoding calls Nominatim. Tests must stay hermetic and must not
# depend on the machine having internet, so it is off by default under test.
REVERSE_GEOCODE_ENABLED = env.bool("REVERSE_GEOCODE_ENABLED", default=not IS_TEST_RUN)

# Database
if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test.sqlite3",
        }
    }
else:
    default_database_url = (
        f'postgres://{env("DB_USER", default="postgres")}:'
        f'{env("DB_PASSWORD", default="postgres")}@'
        f'{env("DB_HOST", default="localhost")}:'
        f'{env("DB_PORT", default="5432")}/'
        f'{env("DB_NAME", default="e_boses")}'
    )
    DATABASES = {
        "default": env.db_url("DATABASE_URL", default=default_database_url),
    }
    # Reuse the Postgres connection across requests: establishing a connection
    # costs tens of milliseconds per request on this machine. CONN_HEALTH_CHECKS
    # quietly discards connections the server dropped while idle.
    DATABASES["default"]["CONN_MAX_AGE"] = 60
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
    if ENABLE_GIS:
        DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"

# Channel layers (Redis)
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Celery uses the same private Redis service as Channels.  OCR work is kept
# on its own queue so CPU-heavy provider calls cannot starve web sockets.
def _celery_redis_url(value):
    """Make hosted rediss URLs explicit about certificate verification.

    redis-py rejects a ``rediss://`` URL without ``ssl_cert_reqs`` at import
    time.  Keeping this normalization here means existing deployments only
    need the URL in .env and local ``delay()`` calls fail gracefully when the
    broker is unavailable.
    """
    if not value or not value.lower().startswith("rediss://"):
        return value
    parsed = urlsplit(value)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query.setdefault("ssl_cert_reqs", "CERT_REQUIRED")
    return urlunsplit(parsed._replace(query=urlencode(query)))


CELERY_BROKER_URL = _celery_redis_url(env("CELERY_BROKER_URL", default=REDIS_URL))
CELERY_RESULT_BACKEND = _celery_redis_url(env("CELERY_RESULT_BACKEND", default=REDIS_URL))

# Django cache: shared Redis instead of the per-process LocMemCache so the API
# server, Celery worker and beat all see the same keys. Beat tasks (POI
# refresh, housekeeping) clear keys in the worker process and the API server
# picks the invalidation up immediately instead of waiting out a process-local
# TTL. CACHE_REDIS_URL defaults to the same private Redis as Channels/Celery;
# the built-in RedisCache backend needs no extra dependency (redis-py ships
# with celery[redis]). Tests stay on LocMemCache so the suite never touches
# the hosted Redis and remains hermetic.
#
# Note: the URL is used as-is. _celery_redis_url() is NOT reused here because it
# appends ssl_cert_reqs=CERT_REQUIRED, which redis-py's own from_url() parser
# rejects (it wants lowercase none/optional/required). redis-py 5.x defaults to
# verifying certs for rediss://, so the raw URL is correct and safe.
if IS_TEST_RUN:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "eboses-tests",
        }
    }
else:
    CACHES = {
        "default": {
            # Prefix-scoped clear(): the stock RedisCacheClient.clear() calls
            # FLUSHDB, which would wipe the Celery broker and Channels data
            # sharing the same Upstash DB (Upstash has no separate DBs).
            "BACKEND": "config.cache_backend.PrefixScopedRedisCache",
            "LOCATION": env("CACHE_REDIS_URL", default=REDIS_URL),
            "KEY_PREFIX": "eboses",
            "TIMEOUT": 300,
            # Django's RedisCacheClient forwards OPTIONS straight into
            # redis-py's ConnectionPool.from_url(), so connection-level kwargs
            # live at the top level here (no CONNECTION_POOL_KWARGS nesting).
            "OPTIONS": {
                # Fail fast when the hosted Redis is unreachable instead of
                # hanging every request for the OS connect timeout.
                "socket_connect_timeout": 3,
                "socket_timeout": 5,
            },
        }
    }
CELERY_TASK_DEFAULT_QUEUE = env("CELERY_TASK_DEFAULT_QUEUE", default="eboses")
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_TIME_LIMIT = env.int("CELERY_TASK_TIME_LIMIT", default=180)
CELERY_TASK_SOFT_TIME_LIMIT = env.int("CELERY_TASK_SOFT_TIME_LIMIT", default=120)
# Task result keys expire after 6 hours instead of the Celery default of 24h.
CELERY_RESULT_EXPIRES = env.int("CELERY_RESULT_EXPIRES", default=21600)
CELERY_BEAT_SCHEDULE = {
    # Status history is only as complete as the number of times we look. Probing
    # on the request path alone means an overnight outage nobody was awake to
    # see is never recorded at all.
    "service-health-sample": {
        "task": "apps.service_status.record_service_health_task",
        "schedule": 300.0,
        "options": {"queue": "eboses"},
    },
    # Deletions blocked by an open report finish themselves once it closes.
    # There is no review screen left to notice, so nothing else would.
    "complete-unblocked-deletions": {
        "task": "apps.accounts.privacy_tasks.complete_unblocked_deletions_task",
        "schedule": 3600.0,
        "options": {"queue": "eboses"},
    },
    "ocr-health-canary": {
        "task": "apps.accounts.ocr_tasks.ocr_health_canary_task",
        "schedule": 300.0,
        "options": {"queue": "eboses"},
    },
    "ocr-recovery": {
        "task": "apps.accounts.ocr_tasks.recover_ocr_cases_task",
        "schedule": 300.0,
        "options": {"queue": "eboses"},
    },
    # Cases abandoned mid-run (worker died while QUEUED/PROCESSING) are invisible
    # to ocr-recovery, so they sat in the officials' pipeline count forever.
    "ocr-stuck-case-rescue": {
        "task": "apps.accounts.ocr_tasks.rescue_stuck_verification_cases_task",
        "schedule": 300.0,
        "options": {"queue": "eboses"},
    },
    # Data minimisation: raw ID images are not kept once verification settles.
    "purge-approved-id-images": {
        "task": "apps.accounts.ocr_tasks.purge_approved_id_images_task",
        "schedule": 24 * 60 * 60.0,
        "options": {"queue": "eboses"},
    },
    # 15s tick so a 45-second critical acknowledgment timeout is actually
    # enforceable; the real deadline comes from each routing rule.
    "emergency-assignment-escalation": {
        "task": "apps.emergencies.tasks.escalate_overdue_emergencies_task",
        "schedule": 15.0,
        "options": {"queue": "eboses"},
    },
    # Once a day, refresh OSM service POIs so the map's Services layer stays
    # current without ever blocking a request on the public Overpass mirrors.
    "refresh-map-service-pois": {
        "task": "apps.emergencies.tasks.refresh_map_service_pois_task",
        "schedule": 24 * 60 * 60.0,
        "options": {"queue": "eboses"},
    },
    # Daily maintenance: flush expired refresh tokens and prune old pings.
    "periodic-housekeeping": {
        "task": "apps.emergencies.tasks.periodic_housekeeping_task",
        "schedule": 24 * 60 * 60.0,
        "options": {"queue": "eboses"},
    },
}

# Password hashing: Argon2id first (modern, fast to verify, memory-hard).
# Existing PBKDF2 hashes upgrade lazily on the user's next successful login.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", "OPTIONS": {"min_length": 8}},
    {"NAME": "apps.accounts.validators.CharacterClassPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = env("MEDIA_URL", default="/media/")
MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "public_media")
PRIVATE_MEDIA_ROOT = env("PRIVATE_MEDIA_ROOT", default=BASE_DIR / "private_media")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication
AUTH_USER_MODEL = "accounts.User"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "200/hour",
        "user": "2000/hour",
        "otp": "5/minute",
        "geocode": "90/minute",
        "auth": "20/minute",
        "login": "5/minute",
        "password_reset": "5/minute",
        "location_ping": "60/minute",
        "assistant": "20/minute",
        "weather_health": "12/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    # Separate from SECRET_KEY so rotating one does not invalidate the other.
    # HS256 needs >=32 bytes; a shorter key would silently weaken every token,
    # so fall back rather than sign with it.
    "SIGNING_KEY": (
        env("JWT_SIGNING_KEY", default="")
        if len(env("JWT_SIGNING_KEY", default="")) >= 32
        else SECRET_KEY
    ),
}

# Background GPS pings older than this many days are pruned by the daily
# housekeeping beat task (apps.emergencies.tasks.periodic_housekeeping_task).
LOCATION_PING_RETENTION_DAYS = env.int("LOCATION_PING_RETENTION_DAYS", default=30)

# Audit log entries older than this many days are pruned by the same task.
AUDIT_LOG_RETENTION_DAYS = env.int("AUDIT_LOG_RETENTION_DAYS", default=180)

# CORS
frontend_url = env("FRONTEND_URL", default="http://localhost:5173") if IS_LOCAL_DEVELOPMENT else env("FRONTEND_URL")
frontend_parts = urlsplit(frontend_url)
frontend_origin = f"{frontend_parts.scheme}://{frontend_parts.netloc}" if frontend_parts.scheme and frontend_parts.netloc else frontend_url

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
_default_cors_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://localhost:5173",
    "https://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://localhost:5174",
    "https://127.0.0.1:5174",
]
if frontend_origin and frontend_origin not in _default_cors_origins:
    _default_cors_origins.append(frontend_origin)
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=_default_cors_origins)
_default_cors_origin_regexes = []
if IS_LOCAL_DEVELOPMENT:
    _default_cors_origin_regexes = [
        r"^https://[a-z0-9-]+\.ngrok-free\.app$",
        r"^https://[a-z0-9-]+\.ngrok-free\.dev$",
        r"^https://[a-z0-9-]+\.ngrok\.app$",
        r"^https://[a-z0-9-]+\.ngrok\.dev$",
        # Any private-network address on a dev port. Laptops move between the
        # barangay Wi-Fi, a phone hotspot and home, and the LAN IP changes each
        # time; without this every move meant hand-editing .env. Private ranges
        # only (RFC1918 + CGNAT), development only.
        r"^https?://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$",
        r"^https?://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$",
        r"^https?://172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}(:\d+)?$",
        r"^https?://100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.\d{1,3}\.\d{1,3}(:\d+)?$",
    ]
CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=_default_cors_origin_regexes)

# Deployment security
# Local/LAN demos use plain HTTP — secure cookies must stay off in development.
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not IS_LOCAL_DEVELOPMENT)
REFRESH_COOKIE_SECURE = env.bool("REFRESH_COOKIE_SECURE", default=not IS_LOCAL_DEVELOPMENT)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not IS_LOCAL_DEVELOPMENT)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = env.bool("CSRF_COOKIE_HTTPONLY", default=False)
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE", default="Lax")
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not IS_LOCAL_DEVELOPMENT)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0 if IS_LOCAL_DEVELOPMENT else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not IS_LOCAL_DEVELOPMENT)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=not IS_LOCAL_DEVELOPMENT)
_default_csrf_trusted = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://localhost:5173",
    "https://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "https://localhost:5174",
    "https://127.0.0.1:5174",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
if IS_LOCAL_DEVELOPMENT:
    _default_csrf_trusted.extend(
        env.list(
            "LOCAL_HTTPS_TUNNEL_ORIGINS",
            default=[
                "https://*.ngrok-free.app",
                "https://*.ngrok-free.dev",
                "https://*.ngrok.app",
                "https://*.ngrok.dev",
            ],
        )
    )
if frontend_origin and frontend_origin not in _default_csrf_trusted:
    _default_csrf_trusted.append(frontend_origin)


def _local_ipv4_addresses():
    """Every non-loopback IPv4 this machine answers on.

    CSRF_TRUSTED_ORIGINS takes no regex, so the LAN address has to be resolved
    rather than pattern-matched. Detecting it means moving between the barangay
    Wi-Fi, a phone hotspot and home no longer needs a .env edit.
    """
    found = set()
    try:
        found.update(socket.gethostbyname_ex(socket.gethostname())[2])
    except Exception:
        pass
    try:
        # Catches adapters the hostname lookup misses (the default-route one).
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            probe.connect(("10.255.255.255", 1))
            found.add(probe.getsockname()[0])
        finally:
            probe.close()
    except Exception:
        pass
    return sorted(a for a in found if a and not a.startswith("127."))


LOCAL_DEV_ORIGIN_PORTS = (5173, 5174, 8000, 8443)

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=_default_csrf_trusted)
# Normalise: a stray space or trailing slash in .env makes an entry that can
# never match the browser's Origin header, which fails in a very confusing way.
CSRF_TRUSTED_ORIGINS = [origin.strip().rstrip("/") for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]

# Added in development even when .env pins the list, so setting one origin by
# hand does not silently switch LAN auto-detection off.
if IS_LOCAL_DEVELOPMENT:
    for _address in _local_ipv4_addresses():
        for _port in LOCAL_DEV_ORIGIN_PORTS:
            for _scheme in ("http", "https"):
                _origin = f"{_scheme}://{_address}:{_port}"
                if _origin not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(_origin)
# Always trust the configured frontend origin (LAN IP demos set FRONTEND_URL).
if frontend_origin and frontend_origin not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [*CSRF_TRUSTED_ORIGINS, frontend_origin]

EMAIL_OTP_PROVIDER = env("EMAIL_OTP_PROVIDER", default="development" if IS_LOCAL_DEVELOPMENT else "django_email")
# SMS codes go through the one barangay gateway (OUTBOUND_SMS_* below), so
# "gateway" is the only meaningful value; "development" prints to the console.
SMS_OTP_PROVIDER = env("SMS_OTP_PROVIDER", default="development" if IS_LOCAL_DEVELOPMENT else "gateway")
if IS_TEST_RUN:
    # Same rule as OUTBOUND_SMS_DRIVER below: a .env pointing at the live
    # Resend account must never send mail from a test run.
    EMAIL_OTP_PROVIDER = "development"
    SMS_OTP_PROVIDER = "development"
# Deprecated: no longer read. Configure OUTBOUND_SMS_URL instead.
SMS_OTP_WEBHOOK_URL = env("SMS_OTP_WEBHOOK_URL", default="")
SMS_OTP_WEBHOOK_TOKEN = env("SMS_OTP_WEBHOOK_TOKEN", default="")
SMS_EMERGENCY_WEBHOOK_TOKEN = env("SMS_EMERGENCY_WEBHOOK_TOKEN", default="")

# ---------------------------------------------------------------------------
# SMS gateway (apps.sms)
# ---------------------------------------------------------------------------
# The barangay runs one Android handset with SMS Forwarder installed. It posts
# received messages to SMS_INBOUND_WEBHOOK_TOKEN-protected /api/sms/inbound/,
# and E-Boses posts back to OUTBOUND_SMS_URL to send replies.
#
# SMS Forwarder builds vary in the JSON field names they expect, so the request
# body is built from OUTBOUND_SMS_PAYLOAD_TEMPLATE. If sending fails with a 4xx,
# correct the template in .env rather than editing apps/sms/gateway.py.
SMS_GATEWAY_NUMBER = env("SMS_GATEWAY_NUMBER", default="")

# .env and .env.example document the SMS Gate handset with SMS_GATE_* names,
# which is what an operator copies out of the app. The driver below reads the
# older OUTBOUND_SMS_* names, so map one onto the other here instead of asking
# anyone to keep two spellings of the same handset in sync.
SMS_GATE_BASE_URL = env("SMS_GATE_BASE_URL", default="")
SMS_GATE_USERNAME = env("SMS_GATE_USERNAME", default="")
SMS_GATE_PASSWORD = env("SMS_GATE_PASSWORD", default="")
SMS_GATE_SIM_NUMBER = env("SMS_GATE_SIM_NUMBER", default="")
SMS_GATE_TIMEOUT_SECONDS = env.float("SMS_GATE_TIMEOUT_SECONDS", default=30.0)
SMS_GATE_DRY_RUN = env.bool("SMS_GATE_DRY_RUN", default=IS_LOCAL_DEVELOPMENT)
SMS_GATE_WEBHOOK_SIGNING_KEY = env("SMS_GATE_WEBHOOK_SIGNING_KEY", default="")

_sms_gate_ready = bool(SMS_GATE_BASE_URL and SMS_GATE_USERNAME and SMS_GATE_PASSWORD)
if SMS_GATE_DRY_RUN:
    _sms_gate_default_driver = "console"
elif _sms_gate_ready:
    _sms_gate_default_driver = "android_sms_gateway"
else:
    _sms_gate_default_driver = "console" if (IS_LOCAL_DEVELOPMENT or IS_TEST_RUN) else "disabled"

OUTBOUND_SMS_DRIVER = env("OUTBOUND_SMS_DRIVER", default=_sms_gate_default_driver)
if IS_TEST_RUN:
    # A `.env` pointed at the barangay's live gateway must never dial out from
    # a test run. The console driver still records the OutboundSmsMessage row
    # tests assert, it just never touches the network.
    OUTBOUND_SMS_DRIVER = "console"
OUTBOUND_SMS_URL = env("OUTBOUND_SMS_URL", default=SMS_GATE_BASE_URL)
# GET gateways take {to} and {body} in the URL itself; POST gateways take
# OUTBOUND_SMS_PAYLOAD_TEMPLATE as the JSON body.
OUTBOUND_SMS_METHOD = env("OUTBOUND_SMS_METHOD", default="POST")
# android-sms-gateway uses HTTP Basic auth (Home screen username/password).
OUTBOUND_SMS_USERNAME = env("OUTBOUND_SMS_USERNAME", default=SMS_GATE_USERNAME)
OUTBOUND_SMS_PASSWORD = env("OUTBOUND_SMS_PASSWORD", default=SMS_GATE_PASSWORD)
# Its webhooks are HMAC-signed with the key from Settings > Webhooks, since the
# app cannot attach a custom auth header.
SMS_WEBHOOK_SIGNING_KEY = env("SMS_WEBHOOK_SIGNING_KEY", default=SMS_GATE_WEBHOOK_SIGNING_KEY)
# Logs the raw webhook body and every candidate digest when a signature does not
# verify. Off by default: the body contains SMS content.
SMS_WEBHOOK_DEBUG = env.bool("SMS_WEBHOOK_DEBUG", default=False)
OUTBOUND_SMS_AUTH_HEADER = env("OUTBOUND_SMS_AUTH_HEADER", default="")
OUTBOUND_SMS_SECRET = env("OUTBOUND_SMS_SECRET", default="")
OUTBOUND_SMS_SIGN_KEY = env("OUTBOUND_SMS_SIGN_KEY", default="")
OUTBOUND_SMS_EXTRA_HEADERS = env("OUTBOUND_SMS_EXTRA_HEADERS", default="")
OUTBOUND_SMS_PAYLOAD_TEMPLATE = env("OUTBOUND_SMS_PAYLOAD_TEMPLATE", default="")
OUTBOUND_SMS_SIM_SLOT = env.int(
    "OUTBOUND_SMS_SIM_SLOT",
    default=int(SMS_GATE_SIM_NUMBER) if SMS_GATE_SIM_NUMBER.isdigit() else 1,
)
OUTBOUND_SMS_TIMEOUT_SECONDS = env.float(
    "OUTBOUND_SMS_TIMEOUT_SECONDS", default=SMS_GATE_TIMEOUT_SECONDS
)
# Falls back to the legacy emergency token so an already-configured handset
# keeps working through the rename.
SMS_INBOUND_WEBHOOK_TOKEN = env("SMS_INBOUND_WEBHOOK_TOKEN", default="") or SMS_EMERGENCY_WEBHOOK_TOKEN
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@localhost")
WEB_PUSH_PUBLIC_KEY = env("WEB_PUSH_PUBLIC_KEY", default="")
WEB_PUSH_PRIVATE_KEY = env("WEB_PUSH_PRIVATE_KEY", default="")
WEB_PUSH_SUBJECT = env("WEB_PUSH_SUBJECT", default=f"mailto:{DEFAULT_FROM_EMAIL}")

SUPPORT_EMAIL = env("SUPPORT_EMAIL", default=DEFAULT_FROM_EMAIL)

# Media storage. With CLOUDINARY_URL set, uploads go to Cloudinary and survive
# a redeploy; without it they stay on local disk. Private files upload as
# type=authenticated either way, and are still only readable through the
# authenticated proxy views.
CLOUDINARY_URL = env("CLOUDINARY_URL", default="")
if CLOUDINARY_URL:
    os.environ.setdefault("CLOUDINARY_URL", CLOUDINARY_URL)
    THIRD_PARTY_APPS = [*THIRD_PARTY_APPS, "cloudinary", "cloudinary_storage"]
    INSTALLED_APPS = ["daphne"] + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS
CLOUDINARY_PRIVATE_URL_TTL_SECONDS = env.int("CLOUDINARY_PRIVATE_URL_TTL_SECONDS", default=300)

# Raw government ID images are deleted this long after verification settles.
# Nothing reads them after that; the hashes that detect duplicates and ID reuse
# are DB columns and survive the deletion.
ID_IMAGE_RETENTION_DAYS = env.int("ID_IMAGE_RETENTION_DAYS", default=30)

# IP reputation gate on login, concern creation and emergency creation.
# Fail-open: an outage or an unreadable reply always allows the request, because
# a blocked SOS is far worse than a VPN slipping through.
IP_INTEL_COUNTRY = env("IP_INTEL_COUNTRY", default="PH")
# PLDT, Globe, DITO, Starlink PH. An allowlisted network is trusted even when
# the provider flags it, because these carry ordinary residents.
IP_INTEL_ALLOWED_ASNS = env.list(
    "IP_INTEL_ALLOWED_ASNS", default=["AS9299", "AS4775", "AS139831", "AS14593"]
)
# X-Forwarded-For is honoured only from these peers; anything else could pick
# its own verdict by setting the header.
TRUSTED_PROXY_IPS = env.list("TRUSTED_PROXY_IPS", default=["127.0.0.1", "::1"])

# A verification case still QUEUED/PROCESSING after this long has lost its
# worker and is requeued by the stuck-case sweeper.
OCR_STUCK_CASE_MINUTES = env.int("OCR_STUCK_CASE_MINUTES", default=15)
# Residents get their own data back without an official approving it; deletion
# still needs a human because it anonymises records other people rely on.
SELF_SERVICE_DATA_EXPORT = env.bool("SELF_SERVICE_DATA_EXPORT", default=True)

# Deletion needs no official approval, but anonymising cannot be undone. The
# resident can withdraw the request for this many days before it is carried out.
ACCOUNT_DELETION_GRACE_DAYS = env.int("ACCOUNT_DELETION_GRACE_DAYS", default=7)

RESEND_API_KEY = env("RESEND_API_KEY", default="")
RESEND_API_URL = env("RESEND_API_URL", default="https://api.resend.com/emails")
RESEND_FROM_EMAIL = env("RESEND_FROM_EMAIL", default=DEFAULT_FROM_EMAIL)
RESEND_FROM_NAME = env("RESEND_FROM_NAME", default="E-Boses")
RESEND_REPLY_TO = env("RESEND_REPLY_TO", default="")
RESEND_DELIVERY_TIMEOUT_SECONDS = env.float("RESEND_DELIVERY_TIMEOUT_SECONDS", default=20.0)
OTP_EMAIL_LOGO_URL = env("OTP_EMAIL_LOGO_URL", default="")
OTP_EMAIL_EXPIRY_TEXT = env("OTP_EMAIL_EXPIRY_TEXT", default="This code expires in 10 minutes.")

ASSISTANT_ENABLED = env.bool("ASSISTANT_ENABLED", default=False)
ASSISTANT_API_KEY = env("ASSISTANT_API_KEY", default="")
ASSISTANT_BASE_URL = env("ASSISTANT_BASE_URL", default="")
ASSISTANT_MODEL = env("ASSISTANT_MODEL", default="")
ASSISTANT_TIMEOUT_SECONDS = env.float("ASSISTANT_TIMEOUT_SECONDS", default=30.0)
ASSISTANT_MAX_TOKENS = env.int("ASSISTANT_MAX_TOKENS", default=220)
ASSISTANT_SESSION_BUDGET = env.int("ASSISTANT_SESSION_BUDGET", default=8)
ASSISTANT_SESSION_BUDGET_WINDOW_SECONDS = env.int(
    "ASSISTANT_SESSION_BUDGET_WINDOW_SECONDS", default=600
)

# Gemma (Ollama Cloud) — the only model that reads report text and photos.
OLLAMA_API_KEY = env("OLLAMA_API_KEY", default="")
OLLAMA_HOST = env("OLLAMA_HOST", default="https://ollama.com")
OLLAMA_TEXT_MODEL = env("OLLAMA_TEXT_MODEL", default="gemma4:31b")
OLLAMA_TIMEOUT_SECONDS = env.int("OLLAMA_TIMEOUT_SECONDS", default=120)
OLLAMA_ENABLE_IMAGE_ANALYSIS = env.bool("OLLAMA_ENABLE_IMAGE_ANALYSIS", default=True)
# Image requests carry a multi-hundred-KB payload and are the ones that time
# out, so they get their own budget instead of borrowing the text timeout.
OLLAMA_IMAGE_TIMEOUT_SECONDS = env.int("OLLAMA_IMAGE_TIMEOUT_SECONDS", default=90)
OLLAMA_IMAGE_RETRY_DELAY_SECONDS = env.float("OLLAMA_IMAGE_RETRY_DELAY_SECONDS", default=2.0)
# Ollama Cloud returns an intermittent 500 on image requests — the same payload
# succeeds on one call and fails seconds later. Attempts back off 2s, 4s, 8s.
OLLAMA_IMAGE_MAX_ATTEMPTS = env.int("OLLAMA_IMAGE_MAX_ATTEMPTS", default=3)
# Small images are refused outright by the cloud vision encoder (a 265x212
# screenshot failed 5/5; upscaled to a 512 short side it succeeded 4/5).
OLLAMA_IMAGE_MIN_SIDE = env.int("OLLAMA_IMAGE_MIN_SIDE", default=512)
OLLAMA_IMAGE_MAX_SIDE = env.int("OLLAMA_IMAGE_MAX_SIDE", default=1024)
OLLAMA_IMAGE_JPEG_QUALITY = env.int("OLLAMA_IMAGE_JPEG_QUALITY", default=82)
OLLAMA_IMAGE_MAX_BYTES = env.int("OLLAMA_IMAGE_MAX_BYTES", default=0)

# SMS AI assist — best-effort rescue of messages the fast parser cannot fully
# read (typos, natural Filipino, landmark-only locations). Purely additive: if
# it is off, slow or wrong, SMS behaves exactly as it does without it. The
# alert is always saved, routed and acknowledged first; this runs afterwards.
SMS_AI_ASSIST_ENABLED = env.bool("SMS_AI_ASSIST_ENABLED", default=False)
SMS_AI_TIMEOUT_SECONDS = env.float("SMS_AI_TIMEOUT_SECONDS", default=2.5)
SMS_AI_MIN_CONFIDENCE = env.float("SMS_AI_MIN_CONFIDENCE", default=0.6)

# IP intelligence — fail-open gate on login, concern filing and emergency
# alerts. When IP_INTEL_URL is empty the feature is off entirely. In dev the
# loopback address is a trusted proxy so X-Forwarded-For works with the mock
# (scripts/mock_iplogs.py); in production set the actual proxy CIDRs.
IP_INTEL_URL = env("IP_INTEL_URL", default="") or env("IP2GEO_API_URL", default="")
IP_INTEL_API_KEY = env("IP_INTEL_API_KEY", default="") or env("IP2GEO_API_KEY", default="")
if IS_TEST_RUN:
    # Same rule as the SMS and email providers: a test run must never reach the
    # live intel service. Tests that exercise the gate override this explicitly.
    IP_INTEL_URL = ""
IP_INTEL_TIMEOUT_SECONDS = env.float("IP_INTEL_TIMEOUT_SECONDS", default=2.5)
IP_INTEL_CACHE_SECONDS = env.int("IP_INTEL_CACHE_SECONDS", default=900)
# "ip2geoapi" (GET /ip/<addr>?key=) or "iplogs" (POST {"ip": ...}), the shape
# scripts/mock_iplogs.py speaks. Auto-detected from the URL when unset.
IP_INTEL_PROVIDER = env("IP_INTEL_PROVIDER", default="")
# ip2geoapi trustScore is 0-100, higher is safer.
IP_INTEL_MIN_TRUST_SCORE = env.int("IP_INTEL_MIN_TRUST_SCORE", default=30)
IP_INTEL_TRUSTED_PROXIES = [
    value.strip()
    for value in env("IP_INTEL_TRUSTED_PROXIES", default="127.0.0.1").split(",")
    if value.strip()
]

# SAM3 privacy segmentation (Roboflow serverless). Runs only when Gemma asks
# for a privacy scan. The key is server-side only and never serialized.
ROBOFLOW_API_KEY = env("ROBOFLOW_API_KEY", default="")
ROBOFLOW_API_URL = env("ROBOFLOW_API_URL", default="https://serverless.roboflow.com")
ROBOFLOW_WORKSPACE = env("ROBOFLOW_WORKSPACE", default="eboses-north")
ROBOFLOW_WORKFLOW_ID = env("ROBOFLOW_WORKFLOW_ID", default="general-segmentation-api-3")
ROBOFLOW_TIMEOUT_SECONDS = env.int("ROBOFLOW_TIMEOUT_SECONDS", default=60)

# OpenCV redaction. Padding matters: a mask cropped exactly to a face still
# leaves identifying edges, so every region is expanded before blurring.
EBOSES_PRIVACY_BLUR_STRENGTH = env.int("EBOSES_PRIVACY_BLUR_STRENGTH", default=31)
EBOSES_PRIVACY_MASK_PADDING = env.float("EBOSES_PRIVACY_MASK_PADDING", default=0.12)

# OCR.space
OCRSPACE_API_KEY = env("OCRSPACE_API_KEY", default="")
OCRSPACE_URL = env("OCRSPACE_URL", default="https://api.ocr.space/parse/image")
OCRSPACE_ENGINE = env.int("OCRSPACE_ENGINE", default=2)
OCRSPACE_LANGUAGE = env("OCRSPACE_LANGUAGE", default="auto")
OCRSPACE_OVERLAY = env.bool("OCRSPACE_OVERLAY", default=True)
OCRSPACE_CONNECT_TIMEOUT = env.int("OCRSPACE_CONNECT_TIMEOUT", default=10)
OCRSPACE_READ_TIMEOUT = env.int("OCRSPACE_READ_TIMEOUT", default=60)
OCRSPACE_MAX_RETRIES = env.int("OCRSPACE_MAX_RETRIES", default=3)
OSM_ROUTE_URL = env("OSM_ROUTE_URL", default="https://router.project-osrm.org/route/v1/driving")
OSM_ROUTE_TIMEOUT_SECONDS = env.int("OSM_ROUTE_TIMEOUT_SECONDS", default=4)

if not IS_LOCAL_DEVELOPMENT and DEBUG:
    raise ImproperlyConfigured("DEBUG must be false outside local development.")
