services:
  - type: static
    name: e-boses
    buildCommand: rm -rf node_modules && rm -f package-lock.json && npm install && cd apps/web && npm run build
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_DEV_HTTPS
        value: "false"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
