from django.urls import path

from .ocr_api import (
    OCRDocumentSampleView,
    OCRDraftConfigurationView,
    OCRHealthRecheckView,
    OCRHealthView,
    OCRAuditView,
    OCRPublishView,
    OCRResetDefaultsView,
    OCRTestRunView,
    ResidenceProofOptionsView,
    VerificationCaseDecisionView,
    VerificationCaseDetailView,
    VerificationCaseListView,
    VerificationCaseRetryView,
    VerificationMeView,
)

from .views import (
    AccountEmailChangeRequestView,
    AccountEmailChangeVerifyView,
    AccountNameChangeConfirmView,
    AccountPhoneChangeRequestView,
    AccountPhoneChangeVerifyView,
    AccountRequestListCreateView,
    AccountRequestManageListView,
    AccountRequestReviewView,
    AccountDataExportView,
    SensitiveAccessAuditView,
    AdminCreateUserView,
    ChangePasswordView,
    CSRFTokenView,
    DeactivateAccountView,
    LoginView,
    LogoutView,
    MeView,
    OnboardCompleteView,
    OTPResendView,
    OTPVerifyView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetVerifyView,
    EmailOTPRequestView,
    EmailOTPVerifyView,
    PhoneOTPRequestView,
    PhoneOTPVerifyView,
    ReactivateAccountView,
    RefreshTokenView,
    CommunityPreviewView,
    EmailAvailabilityView,
    RegisterView,
    ResidenceProofCheckView,
    ResidenceProofDetectView,
    ResidenceProofPreviewMediaView,
    ResidenceProofRawMediaView,
    ResidentSettingsView,
    ResidentDirectoryView,
    StaffAccountUpdateView,
    StaffDirectoryView,
    ResidentMentionSearchView,
    ResidentStatusUpdateView,
    ResponderDirectoryView,
    ResponderUpdateView,
)

urlpatterns = [
    path("residence-proof-options/", ResidenceProofOptionsView.as_view(), name="residence-proof-options"),
    path("verification/me/", VerificationMeView.as_view(), name="verification-me"),
    path("ocr/config/draft/", OCRDraftConfigurationView.as_view(), name="ocr-config-draft"),
    path("ocr/config/publish/", OCRPublishView.as_view(), name="ocr-config-publish"),
    path("ocr/config/reset-defaults/", OCRResetDefaultsView.as_view(), name="ocr-config-reset-defaults"),
    path("ocr/health/", OCRHealthView.as_view(), name="ocr-health"),
    path("ocr/health/recheck/", OCRHealthRecheckView.as_view(), name="ocr-health-recheck"),
    path("ocr/audit/", OCRAuditView.as_view(), name="ocr-audit"),
    path("ocr/tests/", OCRTestRunView.as_view(), name="ocr-tests"),
    path("ocr/document-types/<slug:code>/sample/", OCRDocumentSampleView.as_view(), name="ocr-document-sample"),
    path("ocr/verification-cases/", VerificationCaseListView.as_view(), name="ocr-verification-cases"),
    path("ocr/verification-cases/<int:pk>/", VerificationCaseDetailView.as_view(), name="ocr-verification-case-detail"),
    path("ocr/verification-cases/<int:pk>/decision/", VerificationCaseDecisionView.as_view(), name="ocr-verification-case-decision"),
    path("ocr/verification-cases/<int:pk>/retry/", VerificationCaseRetryView.as_view(), name="ocr-verification-case-retry"),
    path("register/", RegisterView.as_view(), name="auth-register"),
    path("register/email/check/", EmailAvailabilityView.as_view(), name="auth-register-email-check"),
    path("register/community-preview/", CommunityPreviewView.as_view(), name="auth-register-community-preview"),
    path("register/proof/check/", ResidenceProofCheckView.as_view(), name="auth-register-proof-check"),
    path("register/proof/detect/", ResidenceProofDetectView.as_view(), name="auth-register-proof-detect"),
    path("register/phone-otp/request/", PhoneOTPRequestView.as_view(), name="auth-phone-otp-request"),
    path("register/phone-otp/verify/", PhoneOTPVerifyView.as_view(), name="auth-phone-otp-verify"),
    path("register/email-otp/request/", EmailOTPRequestView.as_view(), name="auth-email-otp-request"),
    path("register/email-otp/verify/", EmailOTPVerifyView.as_view(), name="auth-email-otp-verify"),
    path("csrf/", CSRFTokenView.as_view(), name="auth-csrf"),
    path("login/", LoginView.as_view(), name="auth-login"),
    path("refresh/", RefreshTokenView.as_view(), name="auth-refresh"),
    path("logout/", LogoutView.as_view(), name="auth-logout"),
    path("me/", MeView.as_view(), name="auth-me"),
    path("settings/", ResidentSettingsView.as_view(), name="auth-settings"),
    path("account-requests/", AccountRequestListCreateView.as_view(), name="auth-account-requests"),
    path("account-requests/manage/", AccountRequestManageListView.as_view(), name="auth-account-requests-manage"),
    path("account-requests/<int:pk>/review/", AccountRequestReviewView.as_view(), name="auth-account-request-review"),
    path("account-requests/<int:pk>/export/", AccountDataExportView.as_view(), name="auth-account-request-export"),
    path("audit/sensitive-access/", SensitiveAccessAuditView.as_view(), name="auth-sensitive-access-audit"),
    path("account/deactivate/", DeactivateAccountView.as_view(), name="auth-account-deactivate"),
    path("account/reactivate/", ReactivateAccountView.as_view(), name="auth-account-reactivate"),
    path("account/change-password/", ChangePasswordView.as_view(), name="auth-account-change-password"),
    path("account/phone/request-otp/", AccountPhoneChangeRequestView.as_view(), name="auth-account-phone-request-otp"),
    path("account/phone/verify/", AccountPhoneChangeVerifyView.as_view(), name="auth-account-phone-verify"),
    path("account/email/request-otp/", AccountEmailChangeRequestView.as_view(), name="auth-account-email-request-otp"),
    path("account/email/verify/", AccountEmailChangeVerifyView.as_view(), name="auth-account-email-verify"),
    path("account/name-change/confirm/", AccountNameChangeConfirmView.as_view(), name="auth-account-name-change-confirm"),
    path("onboard/complete/", OnboardCompleteView.as_view(), name="auth-onboard-complete"),
    path("otp/resend/", OTPResendView.as_view(), name="auth-otp-resend"),
    path("otp/verify/", OTPVerifyView.as_view(), name="auth-otp-verify"),
    path("password-reset/request/", PasswordResetRequestView.as_view(), name="auth-password-reset-request"),
    path("password-reset/verify/", PasswordResetVerifyView.as_view(), name="auth-password-reset-verify"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="auth-password-reset-confirm"),
    path("media/residence-proofs/<int:pk>/raw/", ResidenceProofRawMediaView.as_view(), name="residence-proof-raw"),
    path("media/residence-proofs/<int:pk>/preview/", ResidenceProofPreviewMediaView.as_view(), name="residence-proof-preview"),
    path("admin/users/", AdminCreateUserView.as_view(), name="auth-admin-create-user"),
    path("staff/", StaffDirectoryView.as_view(), name="auth-staff-directory"),
    path("staff/<int:pk>/", StaffAccountUpdateView.as_view(), name="auth-staff-update"),
    path("residents/", ResidentDirectoryView.as_view(), name="auth-resident-directory"),
    path("residents/mentions/", ResidentMentionSearchView.as_view(), name="auth-resident-mentions"),
    path("residents/<int:pk>/status/", ResidentStatusUpdateView.as_view(), name="auth-resident-status"),
    path("responders/", ResponderDirectoryView.as_view(), name="auth-responder-directory"),
    path("responders/<int:pk>/", ResponderUpdateView.as_view(), name="auth-responder-update"),
]
