from django.urls import path

from .views import (
    EmergencyAcknowledgeView,
    EmergencyAppealCreateView,
    EmergencyAppealListView,
    EmergencyAppealReviewView,
    EmergencyArrivedView,
    EmergencyAssignView,
    EmergencyCancelView,
    EmergencyChatView,
    EmergencyCreateView,
    EmergencyDetailView,
    EmergencyDutyView,
    EmergencyEscalateOverdueView,
    EmergencyQueueView,
    EmergencyLocationPingView,
    EmergencyMediaPreviewView,
    EmergencyMediaRawView,
    EmergencyResolveView,
    MyAssignedEmergencyView,
    MyActiveEmergencyView,
    MyEmergencyHistoryView,
)

urlpatterns = [
    path("", EmergencyCreateView.as_view(), name="emergency-create"),
    path("mine/active/", MyActiveEmergencyView.as_view(), name="emergency-mine-active"),
    path("mine/", MyEmergencyHistoryView.as_view(), name="emergency-mine-history"),
    path("queue/", EmergencyQueueView.as_view(), name="emergency-queue"),
    path("appeals/", EmergencyAppealListView.as_view(), name="emergency-appeal-list"),
    path("appeals/<int:appeal_id>/review/", EmergencyAppealReviewView.as_view(), name="emergency-appeal-review"),
    path("escalate-overdue/", EmergencyEscalateOverdueView.as_view(), name="emergency-escalate-overdue"),
    path("assigned/", MyAssignedEmergencyView.as_view(), name="emergency-assigned"),
    path("duty/", EmergencyDutyView.as_view(), name="emergency-duty"),
    path("media/<int:pk>/preview/", EmergencyMediaPreviewView.as_view(), name="emergency-media-preview"),
    path("media/<int:pk>/raw/", EmergencyMediaRawView.as_view(), name="emergency-media-raw"),
    path("<int:pk>/", EmergencyDetailView.as_view(), name="emergency-detail"),
    path("<int:pk>/chat/", EmergencyChatView.as_view(), name="emergency-chat"),
    path("<int:pk>/assign/", EmergencyAssignView.as_view(), name="emergency-assign"),
    path("<int:pk>/appeals/", EmergencyAppealCreateView.as_view(), name="emergency-appeal-create"),
    path("<int:pk>/cancel/", EmergencyCancelView.as_view(), name="emergency-cancel"),
    path("<int:pk>/location-pings/", EmergencyLocationPingView.as_view(), name="emergency-location-ping"),
    path("<int:pk>/acknowledge/", EmergencyAcknowledgeView.as_view(), name="emergency-acknowledge"),
    path("<int:pk>/arrived/", EmergencyArrivedView.as_view(), name="emergency-arrived"),
    path("<int:pk>/resolve/", EmergencyResolveView.as_view(), name="emergency-resolve"),
]
