from django.urls import path

from .community_api import (
    EmergencyCommentFlagCreateView,
    EmergencyCommunityCommentDetailView,
    EmergencyCommunityCommentListCreateView,
)

from .views import (
    EmergencyAppealCreateView,
    EmergencyAppealListView,
    EmergencyAppealReviewView,
    EmergencyArrivedView,
    EmergencyAssignView,
    EmergencyAssignmentRemoveView,
    EmergencyAssignmentStatusView,
    EmergencyCancelView,
    EmergencyCategoryDetailView,
    EmergencyCategoryListCreateView,
    EmergencyBackupView,
    EmergencyChatAttachmentView,
    EmergencyChatView,
    EmergencyClaimView,
    EmergencyCreateView,
    EmergencyDetailView,
    EmergencyNotificationReplayView,
    EmergencyDispositionView,
    EmergencyDutyView,
    EmergencyEscalateOverdueView,
    EmergencyQueueView,
    EmergencyTypeRoleMapDetailView,
    EmergencyTypeRoleMapListCreateView,
    EmergencyReassignView,
    EmergencyReporterContactView,
    EmergencyResponderContactView,
    EmergencyRespondView,
    EmergencyTransferView,
    EmergencyRouteView,
    ClaimableEmergencyView,
    EmergencyLocationPingView,
    MapDispatchPolicyView,
    EmergencyMediaPreviewView,
    EmergencyMediaRawView,
    EmergencyResolutionEvidencePreviewView,
    EmergencyResolutionEvidenceRawView,
    EmergencyResolveView,
    EmergencySmsInboundView,
    ResponderShiftActiveView,
    ResponderShiftEndView,
    ResponderShiftListView,
    ResponderShiftStartView,
    MyAssignedEmergencyView,
    MyActiveEmergencyView,
    MyEmergencyHistoryView,
)

urlpatterns = [
    path("", EmergencyCreateView.as_view(), name="emergency-create"),
    path("mine/active/", MyActiveEmergencyView.as_view(), name="emergency-mine-active"),
    path("mine/", MyEmergencyHistoryView.as_view(), name="emergency-mine-history"),
    path("queue/", EmergencyQueueView.as_view(), name="emergency-queue"),
    path("claimable/", ClaimableEmergencyView.as_view(), name="emergency-claimable"),
    path("appeals/", EmergencyAppealListView.as_view(), name="emergency-appeal-list"),
    path("appeals/<int:appeal_id>/review/", EmergencyAppealReviewView.as_view(), name="emergency-appeal-review"),
    path("escalate-overdue/", EmergencyEscalateOverdueView.as_view(), name="emergency-escalate-overdue"),
    path("sms-inbound/", EmergencySmsInboundView.as_view(), name="emergency-sms-inbound"),
    path("sms-inbound", EmergencySmsInboundView.as_view(), name="emergency-sms-inbound-no-slash"),
    path("assigned/", MyAssignedEmergencyView.as_view(), name="emergency-assigned"),
    path("duty/", EmergencyDutyView.as_view(), name="emergency-duty"),
    path("map-dispatch-policy/", MapDispatchPolicyView.as_view(), name="map-dispatch-policy"),
    path("categories/", EmergencyCategoryListCreateView.as_view(), name="emergency-category-list"),
    path("categories/<int:pk>/", EmergencyCategoryDetailView.as_view(), name="emergency-category-detail"),
    path("role-maps/", EmergencyTypeRoleMapListCreateView.as_view(), name="emergency-role-map-list"),
    path("role-maps/<int:pk>/", EmergencyTypeRoleMapDetailView.as_view(), name="emergency-role-map-detail"),
    path("shifts/", ResponderShiftListView.as_view(), name="responder-shift-list"),
    path("shifts/active/", ResponderShiftActiveView.as_view(), name="responder-shift-active"),
    path("shifts/start/", ResponderShiftStartView.as_view(), name="responder-shift-start"),
    path("shifts/end/", ResponderShiftEndView.as_view(), name="responder-shift-end"),
    path("media/<int:pk>/preview/", EmergencyMediaPreviewView.as_view(), name="emergency-media-preview"),
    path("media/<int:pk>/raw/", EmergencyMediaRawView.as_view(), name="emergency-media-raw"),
    path("resolution-evidence/<int:pk>/preview/", EmergencyResolutionEvidencePreviewView.as_view(), name="emergency-resolution-evidence-preview"),
    path("resolution-evidence/<int:pk>/raw/", EmergencyResolutionEvidenceRawView.as_view(), name="emergency-resolution-evidence-raw"),
    path("chat-attachments/<int:pk>/raw/", EmergencyChatAttachmentView.as_view(), name="emergency-chat-attachment-raw"),
    path("chat-attachments/<int:pk>/preview/", EmergencyChatAttachmentView.as_view(), {"preview": True}, name="emergency-chat-attachment-preview"),
    path("<int:pk>/", EmergencyDetailView.as_view(), name="emergency-detail"),
    path("<int:pk>/notifications/replay/", EmergencyNotificationReplayView.as_view(), name="emergency-notification-replay"),
    path("<int:pk>/route/", EmergencyRouteView.as_view(), name="emergency-route"),
    path("<int:pk>/reporter-contact/", EmergencyReporterContactView.as_view(), name="emergency-reporter-contact"),
    path("<int:pk>/responder-contact/", EmergencyResponderContactView.as_view(), name="emergency-responder-contact"),
    path(
        "<int:pk>/community-comments/",
        EmergencyCommunityCommentListCreateView.as_view(),
        name="emergency-community-comments",
    ),
    path(
        "<int:pk>/community-comments/<int:comment_id>/",
        EmergencyCommunityCommentDetailView.as_view(),
        name="emergency-community-comment-detail",
    ),
    path(
        "<int:pk>/community-comments/<int:comment_id>/flags/",
        EmergencyCommentFlagCreateView.as_view(),
        name="emergency-community-comment-flag-create",
    ),
    path("<int:pk>/chat/", EmergencyChatView.as_view(), name="emergency-chat"),
    path("<int:pk>/assign/", EmergencyAssignView.as_view(), name="emergency-assign"),
    path(
        "<int:pk>/assignments/<int:assignment_id>/remove/",
        EmergencyAssignmentRemoveView.as_view(),
        name="emergency-assignment-remove",
    ),
    path(
        "<int:pk>/assignments/<int:assignment_id>/status/",
        EmergencyAssignmentStatusView.as_view(),
        name="emergency-assignment-status",
    ),
    path("<int:pk>/reassign/", EmergencyReassignView.as_view(), name="emergency-reassign"),
    path("<int:pk>/claim/", EmergencyClaimView.as_view(), name="emergency-claim"),
    path("<int:pk>/request-backup/", EmergencyBackupView.as_view(), name="emergency-request-backup"),
    path("<int:pk>/en-route/", EmergencyRespondView.as_view(), name="emergency-en-route"),
    path("<int:pk>/transfer/", EmergencyTransferView.as_view(), name="emergency-transfer"),
    path("<int:pk>/appeals/", EmergencyAppealCreateView.as_view(), name="emergency-appeal-create"),
    path("<int:pk>/cancel/", EmergencyCancelView.as_view(), name="emergency-cancel"),
    path("<int:pk>/disposition/", EmergencyDispositionView.as_view(), name="emergency-disposition"),
    path("<int:pk>/location-pings/", EmergencyLocationPingView.as_view(), name="emergency-location-ping"),
    path("<int:pk>/arrived/", EmergencyArrivedView.as_view(), name="emergency-arrived"),
    path("<int:pk>/resolve/", EmergencyResolveView.as_view(), name="emergency-resolve"),
]
