# Generated manually for E-Boses concern workflows.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='ConcernCategory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=50, unique=True)), ('description', models.TextField(blank=True)), ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='ConcernReport', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('barangay', models.CharField(max_length=120)), ('tracking_number', models.CharField(blank=True, max_length=20, unique=True)), ('description', models.TextField()), ('photo_url', models.URLField(blank=True, max_length=500)), ('latitude', models.DecimalField(decimal_places=7, max_digits=10)), ('longitude', models.DecimalField(decimal_places=7, max_digits=10)), ('zone', models.CharField(blank=True, max_length=50)), ('severity_score', models.PositiveSmallIntegerField(default=1)), ('ai_confidence_flag', models.BooleanField(default=False)), ('severity_override', models.PositiveSmallIntegerField(blank=True, null=True)), ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('deferred', 'Deferred'), ('rejected', 'Rejected')], default='submitted', max_length=30)), ('vote_count', models.PositiveIntegerField(default=0)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='concerns.concerncategory')), ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_reports', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='ConcernMedia', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('file', models.FileField(upload_to='concerns/%Y/%m/')), ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=20)), ('original_filename', models.CharField(blank=True, max_length=255)), ('mime_type', models.CharField(blank=True, max_length=120)), ('file_size', models.PositiveIntegerField(default=0)), ('public_url', models.URLField(blank=True, max_length=500)), ('is_public', models.BooleanField(default=False)), ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='concerns.concernreport')), ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_concern_media', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ConcernStatusHistory', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('old_status', models.CharField(max_length=30)), ('new_status', models.CharField(max_length=30)), ('resolution_note', models.TextField(blank=True)), ('updated_at', models.DateTimeField(auto_now_add=True)), ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='concerns.concernreport')), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_status_updates', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ConcernVote', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='concerns.concernreport')), ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_votes', to=settings.AUTH_USER_MODEL))], options={'unique_together': {('report', 'resident')}}),
        migrations.AddIndex(model_name='concernreport', index=models.Index(fields=['resident', 'status'], name='concerns_co_residen_d13af1_idx')),
        migrations.AddIndex(model_name='concernreport', index=models.Index(fields=['barangay', 'status'], name='concerns_co_baranga_ef35a8_idx')),
    ]
