# Generated by Codex on 2026-07-03

import apps.accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Concern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("visibility", models.CharField(choices=[("private", "Private"), ("community", "Community")], default="community", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="concerns", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ConcernMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(storage=apps.accounts.storage.PrivateMediaStorage(), upload_to="concern-media/%Y/%m/")),
                ("preview_file", models.FileField(blank=True, storage=apps.accounts.storage.PrivateMediaStorage(), upload_to="concern-media/previews/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("concern", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="concerns.concern")),
            ],
        ),
    ]
