# Generated by Codex on 2026-07-03

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concerns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concernmedia",
            name="file",
            field=models.FileField(
                storage=apps.accounts.storage.PrivateMediaStorage(),
                upload_to="raw/concern-media/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="concernmedia",
            name="preview_file",
            field=models.FileField(
                blank=True,
                storage=apps.accounts.storage.PublicMediaStorage(),
                upload_to="previews/concern-media/%Y/%m/",
            ),
        ),
    ]
