# Generated by Django 5.2.15 on 2026-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0003_announcement_barangayevent_alter_concern_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='location_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='concern',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='concernmedia',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
