# Generated by Django 5.2.15 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0004_concern_latitude_concern_location_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernmedia',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
