# Generated by Django 5.2.15 on 2026-07-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0005_concernmedia_phash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernAiAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('not_configured', 'Not Configured'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_configured', max_length=24)),
                ('image_objects', models.JSONField(blank=True, default=list)),
                ('yolo_confidence', models.FloatField(blank=True, null=True)),
                ('severity_estimate', models.CharField(blank=True, max_length=32)),
                ('nlp_validity', models.CharField(blank=True, max_length=32)),
                ('nlp_confidence', models.FloatField(blank=True, null=True)),
                ('category_match', models.BooleanField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=120)),
                ('explanation', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='concerns.concern')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('irrelevant', 'Irrelevant'), ('false_info', 'False Information'), ('sensitive', 'Sensitive Content'), ('abusive', 'Abusive Content'), ('other', 'Other')], max_length=24)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='submitted', max_length=24)),
                ('staff_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='concerns.concerncomment')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='concerns.concern')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
