# Generated by Django 5.2.15 on 2026-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0011_alter_concern_validation_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerncomment',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concerncomment',
            name='original_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
