# Generated by Django 5.2.15 on 2026-07-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0012_comment_edit_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='concerns.concern')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['concern', 'created_at'], name='concern_chat_concern_created')],
            },
        ),
    ]
