# Generated by Django 5.2.15 on 2026-07-19 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0014_concernchatattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['barangay', 'latitude', 'longitude'], name='concern_location_lookup'),
        ),
    ]
