# Generated by Django 5.2.15 on 2026-07-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0021_remove_automatic_ai_rejection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concernmedia',
            name='public_preview_state',
        ),
        migrations.AlterField(
            model_name='concernclassificationconfiguration',
            name='mismatch_action',
            field=models.CharField(choices=[('manual_review', 'Flag for official review'), ('reject', 'Reject automatically'), ('request_resubmission', 'Request resubmission')], default='manual_review', max_length=32),
        ),
        migrations.DeleteModel(
            name='ConcernMediaRedaction',
        ),
    ]
