# Generated by Django 5.2.15 on 2026-07-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0022_remove_concernmedia_public_preview_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernaiassessment',
            name='flag_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concernaiassessment',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
