# Generated by Django 5.2.15 on 2026-07-29 04:35

import apps.accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0030_remove_concernclassification_privacy_blur_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerncategory',
            name='custom_icon_label',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='icon_image',
            field=models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='concern-category-icons/'),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='icon_key',
            field=models.CharField(default='tag', max_length=48),
        ),
    ]
