# Generated by Django 5.2.15 on 2026-07-30 09:24

import hashlib
import re

from django.db import migrations, models


STOP_WORDS = {"a", "ang", "at", "ay", "beside", "for", "in", "is", "ito", "mga", "na", "ng", "on", "sa", "the", "this", "to", "with", "yung"}


def _tokens(value):
    return [token for token in re.findall(r"[a-z0-9]+", (value or "").casefold()) if len(token) > 1 and token not in STOP_WORDS]


def _bucket(latitude, longitude, precision=4):
    if latitude is None or longitude is None:
        return ""
    return f"{round(float(latitude), precision):.{precision}f},{round(float(longitude), precision):.{precision}f}"


def backfill_report_fingerprints(apps, schema_editor):
    Concern = apps.get_model("concerns", "Concern")
    for concern in Concern.objects.all().iterator():
        text = " ".join(sorted(set(_tokens(f"{concern.title} {concern.description}"))))
        text_source = f"{concern.category}|{text}"
        bucket = _bucket(concern.latitude, concern.longitude)
        full_source = f"{concern.barangay}|{text_source}|{bucket}"
        concern.report_text_fingerprint = hashlib.sha256(text_source.encode("utf-8")).hexdigest() if text else ""
        concern.report_location_bucket = bucket
        concern.report_fingerprint = hashlib.sha256(full_source.encode("utf-8")).hexdigest() if text and bucket else ""
        concern.save(update_fields=["report_text_fingerprint", "report_location_bucket", "report_fingerprint"])


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0035_alter_concern_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='report_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='concern',
            name='report_location_bucket',
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AddField(
            model_name='concern',
            name='report_text_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_action',
            field=models.CharField(choices=[('warn', 'Warn resident'), ('block', 'Block submission'), ('official_review', 'Submit but flag for official review')], default='warn', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_distance_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_location_precision',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_lookback_days',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='report_duplicate_similarity_threshold',
            field=models.FloatField(default=0.88),
        ),
        migrations.RunPython(backfill_report_fingerprints, migrations.RunPython.noop),
    ]
