# Generated by Django 5.2.15 on 2026-08-14 11:50

import apps.accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0039_align_nlp_model_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='affected_streets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='announcement',
            name='area_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_privacy_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_privacy_state',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='announcement',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='original_image',
            field=models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='announcements/original/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='place_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='barangayevent',
            name='affected_streets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='barangayevent',
            name='area_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='community_observed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concern',
            name='community_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='concerns.concern'),
        ),
        migrations.AddField(
            model_name='concern',
            name='ip_asn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='concern',
            name='ip_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='concern',
            name='ip_org',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='concern',
            name='ip_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='ip_verdict',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='concern',
            name='official_title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='concern',
            name='publication_block_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='concern',
            name='recurrence_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrences', to='concerns.concern'),
        ),
        migrations.AddField(
            model_name='concern',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concern',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concern',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='description_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='location_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='photo_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concernchatattachment',
            name='preview_file',
            field=models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='previews/concern-chat/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='concernchatattachment',
            name='privacy_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='concernchatattachment',
            name='privacy_state',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='resolved_match_detection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='resolved_match_lookback_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='concernmedia',
            name='relevance_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='concernmedia',
            name='relevance_state',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='concernresolutionevidence',
            name='preview_file',
            field=models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='previews/concern-resolution-evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='concernresolutionevidence',
            name='privacy_detected_classes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='concernresolutionevidence',
            name='privacy_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ConcernMergeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merged', 'Merged'), ('unmerged', 'Unmerged'), ('primary_changed', 'Primary changed'), ('suggestion_rejected', 'Suggestion rejected')], max_length=24)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_merge_events', to=settings.AUTH_USER_MODEL)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_events', to='concerns.concern')),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_events_as_primary', to='concerns.concern')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='visible', max_length=16)),
                ('is_official_reply', models.BooleanField(default=False)),
                ('moderation_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='concerns.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='concerns.announcementcomment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['announcement', 'status', 'created_at'], name='ann_comment_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConcernMergeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('method', models.CharField(blank=True, max_length=32)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('rationale', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions', to='concerns.concern')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_merge_decisions', to=settings.AUTH_USER_MODEL)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions_as_primary', to='concerns.concern')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('concern', 'primary'), name='unique_concern_merge_suggestion'), models.CheckConstraint(condition=models.Q(('concern', models.F('primary')), _negated=True), name='merge_suggestion_not_self')],
            },
        ),
    ]
