# Generated by Django 5.2.15 on 2026-08-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0045_harden_position_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentflag',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken'), ('taken_down', 'Taken Down')], default='submitted', max_length=24),
        ),
    ]
