# Generated by Django 5.2.15 on 2026-08-20 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0046_alter_contentflag_status'),
        ('emergencies', '0040_emergencycategory_visible_to_residents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='content_safety_abusive_action',
            field=models.CharField(choices=[('hold', 'Hold for review'), ('auto_reject', 'Reject automatically')], default='hold', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='content_safety_sensitive_action',
            field=models.CharField(choices=[('restrict_hold', 'Restrict & hold for review'), ('auto_blur_accept', 'Auto-blur & accept')], default='restrict_hold', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='content_safety_spam_action',
            field=models.CharField(choices=[('auto_reject', 'Reject automatically'), ('hold', 'Hold for review')], default='auto_reject', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='content_safety_threat_action',
            field=models.CharField(choices=[('accept_flag_notify', 'Accept, flag & notify'), ('hold', 'Hold for review')], default='accept_flag_notify', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='require_ongoing_emergency_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concerncomment',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='concerncomment',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='visible', max_length=16),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='announcement_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='concerns.announcementcomment'),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='auto_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='emergency_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='emergencies.emergencycommunitycomment'),
        ),
        migrations.AlterField(
            model_name='contentflag',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='concerns.concern'),
        ),
        migrations.CreateModel(
            name='LlmDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_kind', models.CharField(choices=[('production', 'Production'), ('simulation', 'Simulation')], max_length=16)),
                ('domain', models.CharField(choices=[('concern', 'Concern'), ('emergency', 'Emergency'), ('community', 'Community content')], max_length=16)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('resident_message', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=32)),
                ('routing_reason', models.CharField(blank=True, max_length=255)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_decision_logs', to='concerns.department')),
                ('concern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_decision_logs', to='concerns.concern')),
                ('content_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_decision_logs', to='concerns.contentflag')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_decision_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['domain', 'run_kind', 'created_at'], name='llm_log_domain_kind_created')],
            },
        ),
    ]
