# Generated by Django 5.2.15 on 2026-08-22 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0048_street_imagery_and_photo_dedup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['status', 'updated_at'], name='concern_status_queue'),
        ),
    ]
