# Generated by Django 5.2.17 on 2026-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0049_concern_concern_status_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_action',
            field=models.CharField(choices=[('flag_notify', 'Accept & flag for the reviewer'), ('hold', 'Hold for review'), ('request_resubmission', 'Ask the resident to resubmit'), ('auto_reject', 'Reject automatically')], default='hold', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_emergency_action',
            field=models.CharField(choices=[('flag_notify', 'Accept & flag for the responder'), ('hold', 'Hold for review')], default='flag_notify', max_length=24),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_min_confidence',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_second_opinion_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
