# Generated by Django 5.2.17 on 2026-08-23 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0050_concernclassificationconfiguration_media_integrity_action_and_more'),
        ('emergencies', '0041_backuprequest_community_emergencyassignmentroute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='concerns.department'),
        ),
        migrations.AddField(
            model_name='barangayevent',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='concern',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='concerns', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='concerncategory',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concern_categories', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='department',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='emergencies.community'),
        ),
        migrations.AlterField(
            model_name='concerncategory',
            name='code',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='concerncategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.SlugField(max_length=80),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='concern',
            index=models.Index(fields=['community', 'status', 'updated_at'], name='concern_comm_status'),
        ),
        migrations.AddIndex(
            model_name='concerncategory',
            index=models.Index(fields=['community', 'is_active', 'name'], name='concern_cat_comm_active'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['community', 'is_active', 'sort_order'], name='concern_dept_comm_active'),
        ),
        migrations.AddConstraint(
            model_name='concerncategory',
            constraint=models.UniqueConstraint(fields=('community', 'code'), name='concerns_cat_community_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='concerncategory',
            constraint=models.UniqueConstraint(fields=('community', 'name'), name='concerns_cat_community_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('community', 'code'), name='concerns_dept_community_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('community', 'name'), name='concerns_dept_community_name_uniq'),
        ),
    ]
