# Generated by Django 5.2.17 on 2026-08-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0051_announcement_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmdecisionlog',
            name='domain',
            field=models.CharField(choices=[('concern', 'Concern'), ('emergency', 'Emergency'), ('verification', 'Verification'), ('community', 'Community content')], max_length=16),
        ),
    ]
