# Generated by Django 5.2.17 on 2026-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0052_alter_llmdecisionlog_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concernclassificationconfiguration',
            name='media_integrity_second_opinion_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
