# Generated by Django 5.2.17 on 2026-08-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0053_media_integrity_second_opinion_default_off'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcernView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='concerns.concern')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('concern', 'viewer'), name='concerns_concernview_uniq')],
            },
        ),
    ]
