# Generated by Django 5.2.17 on 2026-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0054_concernview'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernaiassessment',
            name='severity_reason',
            field=models.TextField(blank=True),
        ),
    ]
