# Generated by Django 5.2.17 on 2026-08-29 13:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_community_scope(apps, schema_editor):
    Concern = apps.get_model("concerns", "Concern")
    Configuration = apps.get_model("concerns", "ConcernClassificationConfiguration")
    Community = apps.get_model("emergencies", "Community")
    Concern.objects.filter(reporter_community__isnull=True).update(
        reporter_community=models.F("community")
    )
    home = Community.objects.filter(code="marikina-heights").first()
    if home:
        Configuration.objects.filter(community__isnull=True).update(community=home)


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0056_concern_notification_subject'),
        ('emergencies', '0049_community_psgc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='reporter_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_concerns', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='concernclassificationconfiguration',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_configuration', to='emergencies.community'),
        ),
        migrations.RunPython(backfill_community_scope, migrations.RunPython.noop),
    ]
