# Generated by Django 5.2.17 on 2026-09-01 13:45

import apps.accounts.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0058_concern_is_anonymous'),
        ('emergencies', '0050_emergencyresolutionevidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='raw/public-comments/%Y/%m/')),
                ('preview_file', models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='previews/public-comments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=12)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('authenticity_status', models.CharField(choices=[('complete', 'Complete'), ('review_required', 'Review required'), ('unavailable', 'Unavailable')], max_length=24)),
                ('authenticity_detail', models.CharField(blank=True, max_length=255)),
                ('street_imagery', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='concerns.announcementcomment')),
                ('concern_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='concerns.concerncomment')),
                ('emergency_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='emergencies.emergencycommunitycomment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('announcement_comment__isnull', True), ('concern_comment__isnull', False), ('emergency_comment__isnull', True)), models.Q(('announcement_comment__isnull', False), ('concern_comment__isnull', True), ('emergency_comment__isnull', True)), models.Q(('announcement_comment__isnull', True), ('concern_comment__isnull', True), ('emergency_comment__isnull', False)), _connector='OR'), name='public_comment_attachment_one_parent')],
            },
        ),
    ]
