from django.urls import path

from .community_api import ConcernCancelView, ConcernReopenRequestView
from .merge_api import (
    ConcernMergeHistoryView,
    ConcernMergeView,
    ConcernSetPrimaryView,
    ConcernUnmergeView,
    MergeSuggestionDecideView,
    MergeSuggestionListView,
)
from .views import (
    AssignedConcernListView,
    ConcernAppealCreateView,
    ConcernAppealListView,
    ConcernAppealReviewView,
    ConcernAssignView,
    ConcernClarificationReplyView,
    ConcernClarificationRequestView,
    ConcernChatView,
    ConcernChatReadView,
    ConcernChatTypingView,
    ConcernChatAttachmentRawView,
    ConcernCommentCreateView,
    ConcernCategoryDetailView,
    ConcernCategoryOptionsView,
    ConcernCategoryListCreateView,
    ConcernFormFieldListCreateView,
    ConcernCommentDetailView,
    PublicCommentAttachmentView,
    ConcernDetailView,
    ConcernFeedView,
    ConcernListCreateView,
    ConcernMediaCheckView,
    ConcernMediaCheckJobStatusView,
    ConcernMediaPreviewView,
    ConcernMediaPrivacyReprocessView,
    ConcernMediaRawView,
    ConcernMediaRedactionView,
    ConcernOfficialRemarkCreateView,
    ConcernResolutionEvidencePreviewView,
    ConcernResolutionEvidenceRawView,
    ConcernPublicDetailView,
    ConcernPublishView,
    ConcernStatusUpdateView,
    ConcernTimelineEntryView,
    ConcernSummaryView,
    ConcernVoteView,
    ContentFlagCreateView,
    ContentFlagListView,
    ContentFlagReviewView,
    DepartmentChatMessageListCreateView,
    DepartmentChatThreadListCreateView,
    DepartmentDetailView,
    DepartmentListCreateView,
    DepartmentMembersView,
    DesignationDetailView,
    DesignationListCreateView,
    ManagedConcernListView,
    MyConcernListView,
    PositionDetailView,
    PositionListCreateView,
    RoutingRuleDetailView,
    RoutingRuleListCreateView,
)
from .classification_api import (
    CommunityModerationSimulationView,
    LlmDecisionLogListView,
    LlmDecisionLogStreetImageryView,
    OfficialClassificationActivityView,
    OfficialClassificationResetView,
    OfficialClassificationSampleGeneratorView,
    OfficialClassificationSubmissionTestView,
    OfficialClassificationStatsView,
    OfficialClassificationTextTestView,
    OfficialClassificationView,
    ResidentConcernPrecheckView,
    ResidentPrecheckJobStatusView,
)
from apps.emergencies.simulation_api import EmergencySimulationView
from apps.sms.simulation_api import SmsSimulationView

urlpatterns = [

    path("categories/", ConcernCategoryOptionsView.as_view(), name="concern-categories"),
    path("admin/departments/", DepartmentListCreateView.as_view(), name="concern-admin-departments"),
    path("admin/departments/<int:pk>/", DepartmentDetailView.as_view(), name="concern-admin-department-detail"),
    path("admin/departments/<int:department_id>/members/", DepartmentMembersView.as_view(), name="concern-admin-department-members"),
    path("admin/positions/", PositionListCreateView.as_view(), name="concern-admin-positions"),
    path("admin/positions/<int:pk>/", PositionDetailView.as_view(), name="concern-admin-position-detail"),
    path("admin/designations/", DesignationListCreateView.as_view(), name="concern-admin-designations"),
    path("admin/designations/<int:pk>/", DesignationDetailView.as_view(), name="concern-admin-designation-detail"),
    path("admin/categories/", ConcernCategoryListCreateView.as_view(), name="concern-admin-categories"),
    path("admin/categories/<int:pk>/", ConcernCategoryDetailView.as_view(), name="concern-admin-category-detail"),
    path("admin/categories/<int:category_id>/fields/", ConcernFormFieldListCreateView.as_view(), name="concern-admin-category-fields"),
    path("admin/routing-rules/", RoutingRuleListCreateView.as_view(), name="concern-admin-routing-rules"),
    path("admin/routing-rules/<int:pk>/", RoutingRuleDetailView.as_view(), name="concern-admin-routing-rule-detail"),
    path("department-chat/threads/", DepartmentChatThreadListCreateView.as_view(), name="department-chat-thread-list"),
    path("department-chat/threads/<int:thread_id>/messages/", DepartmentChatMessageListCreateView.as_view(), name="department-chat-message-list"),
    path("classification/", OfficialClassificationView.as_view(), name="classification-configuration"),
    path("classification/stats/", OfficialClassificationStatsView.as_view(), name="classification-stats"),
    path("classification/activity/", OfficialClassificationActivityView.as_view(), name="classification-activity"),
    path("classification/reset/", OfficialClassificationResetView.as_view(), name="classification-reset"),
    path("classification/test-text/", OfficialClassificationTextTestView.as_view(), name="classification-test-text"),
    path("classification/test-submission/", OfficialClassificationSubmissionTestView.as_view(), name="classification-test-submission"),
    path("classification/generate-sample/", OfficialClassificationSampleGeneratorView.as_view(), name="classification-generate-sample"),
    path("classification/precheck/", ResidentConcernPrecheckView.as_view(), name="classification-precheck"),
    path("classification/precheck/jobs/<str:job_id>/", ResidentPrecheckJobStatusView.as_view(), name="classification-precheck-job"),
    path("classification/test-emergency/", EmergencySimulationView.as_view(), name="classification-test-emergency"),
    path("classification/test-sms/", SmsSimulationView.as_view(), name="classification-test-sms"),
    path("classification/test-community/", CommunityModerationSimulationView.as_view(), name="classification-test-community"),
    path("classification/log/", LlmDecisionLogListView.as_view(), name="classification-log"),
    path("classification/log/<int:pk>/street-view/", LlmDecisionLogStreetImageryView.as_view(), name="classification-log-street-view"),
    path("", ConcernListCreateView.as_view(), name="concern-create"),
    path("media/check/", ConcernMediaCheckView.as_view(), name="concern-media-check"),
    path("media/check/jobs/<str:job_id>/", ConcernMediaCheckJobStatusView.as_view(), name="concern-media-check-job"),
    path("mine/", MyConcernListView.as_view(), name="concern-mine"),
    path("assigned/", AssignedConcernListView.as_view(), name="concern-assigned"),
    path("manage/", ManagedConcernListView.as_view(), name="concern-manage"),
    path("appeals/", ConcernAppealListView.as_view(), name="concern-appeal-list"),
    path("appeals/<int:appeal_id>/review/", ConcernAppealReviewView.as_view(), name="concern-appeal-review"),
    path("flags/", ContentFlagListView.as_view(), name="content-flag-list"),
    path("flags/<int:pk>/review/", ContentFlagReviewView.as_view(), name="content-flag-review"),
    path("feed/", ConcernFeedView.as_view(), name="concern-feed"),
    path("summary/", ConcernSummaryView.as_view(), name="concern-summary"),
    path("merge-suggestions/", MergeSuggestionListView.as_view(), name="merge-suggestions"),
    path(
        "merge-suggestions/<int:pk>/decide/",
        MergeSuggestionDecideView.as_view(),
        name="merge-suggestion-decide",
    ),
    path("by-public-id/<uuid:public_id>/", ConcernPublicDetailView.as_view(), name="concern-public-detail"),
    path("<uuid:public_id>/", ConcernPublicDetailView.as_view(), name="concern-public-detail-direct"),
    path("<int:pk>/publish/", ConcernPublishView.as_view(), name="concern-publish"),
    path("<int:pk>/", ConcernDetailView.as_view(), name="concern-detail"),
    path("<int:pk>/status/", ConcernStatusUpdateView.as_view(), name="concern-status-update"),
    path("<int:pk>/assign/", ConcernAssignView.as_view(), name="concern-assign"),
    path("<int:pk>/clarifications/", ConcernClarificationRequestView.as_view(), name="concern-clarification-request"),
    path("<int:pk>/clarifications/<int:clarification_id>/reply/", ConcernClarificationReplyView.as_view(), name="concern-clarification-reply"),
    path("<int:pk>/appeals/", ConcernAppealCreateView.as_view(), name="concern-appeal-create"),
    path("<int:pk>/remarks/", ConcernOfficialRemarkCreateView.as_view(), name="concern-remark-create"),
    path("<int:pk>/chat/", ConcernChatView.as_view(), name="concern-chat"),
    path("<int:pk>/chat/read/", ConcernChatReadView.as_view(), name="concern-chat-read"),
    path("<int:pk>/chat/typing/", ConcernChatTypingView.as_view(), name="concern-chat-typing"),
    path("<int:pk>/timeline/", ConcernTimelineEntryView.as_view(), name="concern-timeline-entry"),
    path("chat-media/<int:pk>/", ConcernChatAttachmentRawView.as_view(), name="concern-chat-media-raw"),
    path("<int:pk>/reopen-request/", ConcernReopenRequestView.as_view(), name="concern-reopen-request"),
    path("<int:pk>/cancel/", ConcernCancelView.as_view(), name="concern-cancel"),
    path("<int:pk>/merge/", ConcernMergeView.as_view(), name="concern-merge"),
    path("<int:pk>/unmerge/", ConcernUnmergeView.as_view(), name="concern-unmerge"),
    path("<int:pk>/set-primary/", ConcernSetPrimaryView.as_view(), name="concern-set-primary"),
    path("<int:pk>/merge-history/", ConcernMergeHistoryView.as_view(), name="concern-merge-history"),
    path("<int:pk>/vote/", ConcernVoteView.as_view(), name="concern-vote"),
    path("<int:pk>/comments/", ConcernCommentCreateView.as_view(), name="concern-comment-create"),
    path("comment-media/<int:pk>/preview/", PublicCommentAttachmentView.as_view(), {"preview": True}, name="comment-media-preview"),
    path("comment-media/<int:pk>/raw/", PublicCommentAttachmentView.as_view(), name="comment-media-raw"),
    path(
        "<int:pk>/comments/<int:comment_id>/",
        ConcernCommentDetailView.as_view(),
        name="concern-comment-detail",
    ),
    path("<int:pk>/flags/", ContentFlagCreateView.as_view(), name="content-flag-create"),
    path("media/<int:pk>/raw/", ConcernMediaRawView.as_view(), name="concern-media-raw"),
    path("media/<int:pk>/preview/", ConcernMediaPreviewView.as_view(), name="concern-media-preview"),
    path("media/<int:pk>/redactions/", ConcernMediaRedactionView.as_view(), name="concern-media-redactions"),
    path(
        "media/<int:pk>/redactions/<int:redaction_id>/",
        ConcernMediaRedactionView.as_view(),
        name="concern-media-redaction-detail",
    ),
    path(
        "media/<int:pk>/privacy/reprocess/",
        ConcernMediaPrivacyReprocessView.as_view(),
        name="concern-media-privacy-reprocess",
    ),
    path(
        "resolution-evidence/<int:pk>/raw/",
        ConcernResolutionEvidenceRawView.as_view(),
        name="concern-resolution-evidence-raw",
    ),
    path(
        "resolution-evidence/<int:pk>/preview/",
        ConcernResolutionEvidencePreviewView.as_view(),
        name="concern-resolution-evidence-preview",
    ),
]
