# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencymedia",
            name="sha256_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
