# Generated by Django 5.2.15 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_emergencymedia_sha256_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencymedia',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
