# Generated by Claude Code on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergencies", "0004_emergencyappeal_emergencyescalation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapGeometry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("boundary", "Boundary"), ("street", "Street")], max_length=16)),
                ("name", models.CharField(db_index=True, max_length=160)),
                ("osm_type", models.CharField(max_length=1)),
                ("osm_id", models.PositiveBigIntegerField()),
                ("street_type", models.CharField(blank=True, max_length=40)),
                ("geometry", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["kind", "name", "osm_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="mapgeometry",
            constraint=models.UniqueConstraint(fields=("kind", "osm_type", "osm_id"), name="unique_map_geometry_osm"),
        ),
        migrations.AddIndex(
            model_name="mapgeometry",
            index=models.Index(fields=["kind", "is_active", "name"], name="emerg_map_geom_kind_active"),
        ),
    ]
