# Generated by Django 5.2.15 on 2026-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0009_alter_emergencyresponderassignment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapServicePoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poi_type', models.CharField(choices=[('barangay_hall', 'Barangay Hall'), ('health_center', 'Health Center'), ('hospital', 'Hospital'), ('police', 'Police'), ('fire', 'Fire Station'), ('tanod', 'Tanod'), ('bdrrmo', 'BDRRMO'), ('evacuation', 'Evacuation'), ('school', 'School'), ('pharmacy', 'Pharmacy'), ('clinic', 'Clinic'), ('dentist', 'Dentist'), ('veterinary', 'Veterinary'), ('ambulance', 'Ambulance'), ('security', 'Security'), ('community', 'Community'), ('other', 'Other')], default='other', max_length=40)),
                ('label', models.CharField(blank=True, help_text='Short map label; defaults from type if blank.', max_length=80)),
                ('sector', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=16)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('source', models.CharField(choices=[('admin', 'Admin managed'), ('curated', 'Curated seed')], default='admin', max_length=16)),
                ('osm_type', models.CharField(blank=True, help_text='OSM element type N/W/R when this row overrides or suppresses an OSM feature.', max_length=1)),
                ('osm_id', models.PositiveBigIntegerField(blank=True, help_text='OSM id to replace (active) or hide (inactive).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on map. If False and osm_id is set, hide that OSM POI.')),
                ('notes', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Higher priority sorts first when merging duplicates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map service POI',
                'verbose_name_plural': 'Map service POIs',
                'ordering': ['-priority', 'name', 'id'],
                'indexes': [models.Index(fields=['is_active', 'poi_type'], name='emerg_svcpoi_active_type'), models.Index(fields=['osm_type', 'osm_id'], name='emerg_svcpoi_osm')],
            },
        ),
    ]
