# Generated by Django 5.2.15 on 2026-07-19 11:50

import apps.accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0012_respondershift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.accounts.storage.PrivateMediaStorage(), upload_to='raw/emergency-chat/%Y/%m/')),
                ('preview_file', models.FileField(blank=True, storage=apps.accounts.storage.PublicMediaStorage(), upload_to='previews/emergency-chat/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=12)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('phash', models.CharField(blank=True, db_index=True, max_length=16)),
                ('analysis_status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('unavailable', 'Unavailable')], max_length=16)),
                ('analysis', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emergencychatmessage',
            name='body',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='emergencychatattachment',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='emergencies.emergencychatmessage'),
        ),
    ]
