# Generated by Django 5.2.15 on 2026-07-19 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0013_emergencychatattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['status', 'barangay', 'created_at'], name='emerg_alert_status_brgy'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['latitude', 'longitude'], name='emerg_alert_coords'),
        ),
        migrations.AddIndex(
            model_name='emergencylocationping',
            index=models.Index(fields=['assignment', 'created_at'], name='emerg_ping_assignment_time'),
        ),
        migrations.AddIndex(
            model_name='emergencylocationping',
            index=models.Index(fields=['responder', 'created_at'], name='emerg_ping_responder_time'),
        ),
        migrations.AddIndex(
            model_name='respondershift',
            index=models.Index(fields=['responder', 'ended_at'], name='shift_responder_active'),
        ),
    ]
