# Generated by Django 5.2.15 on 2026-07-27 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0016_mapdispatchpolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto route'), ('manual', 'Manual assignment'), ('escalation', 'Escalation'), ('claim', 'Responder claim')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='status_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emergencyresponderassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('acknowledged', 'Acknowledged'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('assisting', 'Assisting'), ('resolved', 'Resolved'), ('declined', 'Declined'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='assigned', max_length=32),
        ),
        migrations.CreateModel(
            name='EmergencyTypeRoleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('crime', 'Crime'), ('disaster', 'Disaster'), ('other', 'Other')], max_length=32)),
                ('responder_unit', models.CharField(max_length=24)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('requires_shift', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'id'],
                'indexes': [models.Index(fields=['emergency_type', 'is_active', '-priority'], name='emerg_role_map_lookup')],
                'constraints': [models.UniqueConstraint(fields=('emergency_type', 'responder_unit'), name='emerg_role_map_type_unit_uniq')],
            },
        ),
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='role_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='emergencies.emergencytyperolemap'),
        ),
        migrations.CreateModel(
            name='EmergencyAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assignment_actions', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='emergencies.emergencyalert')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emergencies.emergencyresponderassignment')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_assignment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['alert', 'created_at'], name='emerg_assign_log_lookup')],
            },
        ),
    ]
