# Generated by Django 5.2.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0017_emergencyresponderassignment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]