# Generated by Django 5.2.15 on 2026-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0019_role_map_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='emergency_sms_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
