# Generated by Django 5.2.15 on 2026-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0023_emergencycategory_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='type',
            field=models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('crime', 'Crime'), ('disaster', 'Disaster'), ('child_protection', 'Child Protection'), ('domestic_violence', 'Domestic Violence'), ('drug_related', 'Drug-Related Incident')], max_length=32),
        ),
    ]
