# Generated by Django 5.2.15 on 2026-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0025_remove_other_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='category_needs_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='location_confidence',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('reported', 'Reported area only'), ('unknown', 'Unknown'), ('outside_area', 'Outside service area')], default='confirmed', max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reported_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reporter_contact_number',
            field=models.CharField(blank=True, help_text='Sender number for SMS-originated alerts. Masked everywhere except the audited reveal endpoint.', max_length=24),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reporter_verification',
            field=models.CharField(choices=[('account', 'Signed-in account'), ('registered', 'Registered mobile number'), ('unverified', 'Mobile number not verified'), ('needs_review', 'Account match requires review')], default='account', max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='resolved_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reverse_geocoding_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('pending', 'Pending')], default='skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='triage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='unresolved_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
