# Generated by Django 5.2.15 on 2026-08-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0039_align_nlp_model_default'),
        ('emergencies', '0027_seed_sms_emergency_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='acknowledgment_timeout_seconds',
            field=models.PositiveIntegerField(default=300, help_text='Seconds before an unacknowledged assignment is reassigned or escalated.'),
        ),
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='auto_backup_on_timeout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='escalation_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_escalation_maps', to='concerns.department'),
        ),
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='service_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='supporting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_support_maps', to='concerns.department'),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('submitted', 'Emergency Received'), ('routing', 'Finding Available Responder'), ('routed', 'Responder Assigned'), ('awaiting_acknowledgment', 'Awaiting Responder'), ('acknowledged', 'Responder Confirmed'), ('en_route', 'Responder En Route'), ('nearby', 'Responder Nearby'), ('arrived', 'Responder at Scene'), ('backup_requested', 'Backup Requested'), ('backup_assigned', 'Backup Assigned'), ('in_progress', 'Response in Progress'), ('transfer_required', 'Transfer Required'), ('escalation_required', 'Escalation Required'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='emergencystatusevent',
            name='status',
            field=models.CharField(choices=[('submitted', 'Emergency Received'), ('routing', 'Finding Available Responder'), ('routed', 'Responder Assigned'), ('awaiting_acknowledgment', 'Awaiting Responder'), ('acknowledged', 'Responder Confirmed'), ('en_route', 'Responder En Route'), ('nearby', 'Responder Nearby'), ('arrived', 'Responder at Scene'), ('backup_requested', 'Backup Requested'), ('backup_assigned', 'Backup Assigned'), ('in_progress', 'Response in Progress'), ('transfer_required', 'Transfer Required'), ('escalation_required', 'Escalation Required'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], max_length=32),
        ),
    ]
