# Generated by Django 5.2.15 on 2026-08-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0029_seed_routing_timeouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='duty_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='duty_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='hotlines',
            field=models.JSONField(blank=True, default=list, help_text='[{"label": "Marikina Rescue", "number": "161"}]'),
        ),
    ]
