# Generated by Django 5.2.15 on 2026-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0030_mapdispatchpolicy_duty_hours_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapAddressPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(default='N', max_length=1)),
                ('osm_id', models.PositiveBigIntegerField()),
                ('house_number', models.CharField(blank=True, max_length=32)),
                ('street', models.CharField(blank=True, db_index=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='emerg_addr_coords')],
                'constraints': [models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='unique_map_address_osm')],
            },
        ),
    ]
