# Generated by Django 5.2.15 on 2026-08-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0031_mapaddresspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencystatusevent',
            name='event_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='emergencystatusevent',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(choices=[('submitted', 'Emergency Received'), ('routing', 'Finding Available Responder'), ('routed', 'Responder Assigned'), ('awaiting_acknowledgment', 'Awaiting Responder'), ('acknowledged', 'Responder Confirmed'), ('en_route', 'Responder En Route'), ('nearby', 'Responder Nearby'), ('arrived', 'Responder at Scene'), ('resident_safe', 'Resident Reported Safe'), ('backup_requested', 'Backup Requested'), ('backup_assigned', 'Backup Assigned'), ('in_progress', 'Response in Progress'), ('transfer_required', 'Transfer Required'), ('escalation_required', 'Escalation Required'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='emergencystatusevent',
            name='status',
            field=models.CharField(choices=[('submitted', 'Emergency Received'), ('routing', 'Finding Available Responder'), ('routed', 'Responder Assigned'), ('awaiting_acknowledgment', 'Awaiting Responder'), ('acknowledged', 'Responder Confirmed'), ('en_route', 'Responder En Route'), ('nearby', 'Responder Nearby'), ('arrived', 'Responder at Scene'), ('resident_safe', 'Resident Reported Safe'), ('backup_requested', 'Backup Requested'), ('backup_assigned', 'Backup Assigned'), ('in_progress', 'Response in Progress'), ('transfer_required', 'Transfer Required'), ('escalation_required', 'Escalation Required'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('invalid', 'Invalid'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], max_length=32),
        ),
    ]
