# Generated by Django 5.2.15 on 2026-08-07 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0032_emergencystatusevent_event_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emergencylocationping',
            index=models.Index(fields=['created_at'], name='emerg_ping_created_at'),
        ),
    ]
