# Generated by Django 5.2.15 on 2026-08-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0040_announcement_affected_streets_and_more'),
        ('emergencies', '0033_emergencylocationping_emerg_ping_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='ai_assist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='ip_asn',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='ip_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='ip_org',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='ip_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='ip_verdict',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reopen_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='resolution_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='source_concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_emergencies', to='concerns.concern'),
        ),
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='travel_profile',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='EmergencyCommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden'), ('removed', 'Removed')], default='visible', max_length=16)),
                ('is_official_update', models.BooleanField(default=False)),
                ('moderation_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='emergencies.emergencyalert')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_community_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='emergencies.emergencycommunitycomment')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_emergency_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['alert', 'status', 'created_at'], name='emerg_comment_alert_status')],
            },
        ),
    ]
