# Generated by Django 5.2.15 on 2026-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0036_deactivate_removed_emergency_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='covered',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'boundary'}, related_name='covered_by_policies', to='emergencies.mapgeometry'),
        ),
        migrations.AddField(
            model_name='mapgeometry',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mapgeometry',
            name='locality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mapgeometry',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='emergencies.mapgeometry'),
        ),
    ]
