# Generated by Django 5.2.17 on 2026-08-23 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0050_concernclassificationconfiguration_media_integrity_action_and_more'),
        ('emergencies', '0040_emergencycategory_visible_to_residents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('urgency', models.CharField(default='normal', max_length=16)),
                ('idempotency_key', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('pending_manual', 'Pending manual assignment'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('center_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('bbox_min_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bbox_max_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bbox_min_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bbox_max_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('boundary_revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAssignmentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('calculating', 'Calculating'), ('ok', 'Ready'), ('stale', 'Stale'), ('unavailable', 'Unavailable')], default='calculating', max_length=16)),
                ('profile', models.CharField(default='car', max_length=8)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('eta_seconds', models.FloatField(blank=True, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('origin_snap', models.JSONField(blank=True, null=True)),
                ('destination_snap', models.JSONField(blank=True, null=True)),
                ('approach', models.JSONField(blank=True, null=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('route_revision', models.PositiveIntegerField(default=1)),
                ('destination_revision', models.PositiveIntegerField(default=1)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='emergencytyperolemap',
            name='emerg_role_map_type_dept_uniq',
        ),
        migrations.RemoveIndex(
            model_name='emergencycategory',
            name='emerg_cat_active_order',
        ),
        migrations.RemoveIndex(
            model_name='emergencytyperolemap',
            name='emerg_role_map_lookup',
        ),
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='is_cross_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencycategory',
            name='code',
            field=models.SlugField(max_length=80),
        ),
        migrations.AddField(
            model_name='backuprequest',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_requests', to='emergencies.emergencyalert'),
        ),
        migrations.AddField(
            model_name='backuprequest',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_requests', to='emergencies.emergencyresponderassignment'),
        ),
        migrations.AddField(
            model_name='backuprequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_emergency_backups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backuprequest',
            name='target_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_requests', to='concerns.department'),
        ),
        migrations.AddField(
            model_name='community',
            name='boundary',
            field=models.OneToOneField(blank=True, limit_choices_to={'kind': 'boundary'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community', to='emergencies.mapgeometry'),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_alerts', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='emergencycategory',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_categories', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='emergencyresponderassignment',
            name='responding_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responder_assignments', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='emergencytyperolemap',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_role_maps', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='mapdispatchpolicy',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_policy', to='emergencies.community'),
        ),
        migrations.AddIndex(
            model_name='emergencyalert',
            index=models.Index(fields=['community', 'status', 'created_at'], name='emerg_alert_comm_status'),
        ),
        migrations.AddIndex(
            model_name='emergencycategory',
            index=models.Index(fields=['community', 'is_active', 'sort_order'], name='emerg_cat_comm_active'),
        ),
        migrations.AddIndex(
            model_name='emergencytyperolemap',
            index=models.Index(fields=['community', 'emergency_type', 'is_active', '-priority'], name='emerg_role_map_lookup'),
        ),
        migrations.AddConstraint(
            model_name='emergencycategory',
            constraint=models.UniqueConstraint(fields=('community', 'code'), name='emerg_cat_community_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='emergencytyperolemap',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('community', 'emergency_type', 'department'), name='emerg_role_map_comm_type_dept_uniq'),
        ),
        migrations.AddField(
            model_name='emergencyassignmentroute',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_route', to='emergencies.emergencyresponderassignment'),
        ),
        migrations.AddIndex(
            model_name='backuprequest',
            index=models.Index(fields=['alert', 'status', 'created_at'], name='emerg_backup_alert_status'),
        ),
        migrations.AddIndex(
            model_name='backuprequest',
            index=models.Index(fields=['target_department', 'status'], name='emerg_backup_dept_status'),
        ),
        migrations.AddConstraint(
            model_name='backuprequest',
            constraint=models.UniqueConstraint(fields=('alert', 'requested_by', 'idempotency_key'), name='emerg_backup_idempotent'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['status', 'bbox_min_latitude', 'bbox_max_latitude'], name='emerg_comm_lat_bounds'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['status', 'bbox_min_longitude', 'bbox_max_longitude'], name='emerg_comm_lng_bounds'),
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.CheckConstraint(condition=models.Q(('boundary_revision__gte', 1)), name='emerg_comm_revision_gte_1'),
        ),
        migrations.AddIndex(
            model_name='emergencyassignmentroute',
            index=models.Index(fields=['status', 'updated_at'], name='emerg_route_status_time'),
        ),
    ]
