# Generated by Django 5.2.17 on 2026-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0041_backuprequest_community_emergencyassignmentroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMigrationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=64)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['model_label', 'object_id'],
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_id', 'reason'), name='emerg_comm_migration_issue_uniq')],
            },
        ),
    ]
