# Generated by Django 5.2.17 on 2026-08-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0042_communitymigrationissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapservicepoi',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_pois', to='emergencies.community'),
        ),
        migrations.AddIndex(
            model_name='mapservicepoi',
            index=models.Index(fields=['community', 'is_active', 'poi_type'], name='emerg_svcpoi_comm_type'),
        ),
    ]
