# Generated by Django 5.2.17 on 2026-08-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0044_backfill_default_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='boundary',
            field=models.OneToOneField(blank=True, limit_choices_to={'kind': 'boundary'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community', to='emergencies.mapgeometry'),
        ),
    ]
