# Generated by Django 5.2.17 on 2026-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0045_community_boundary_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='media_integrity',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
