# Generated by Django 5.2.17 on 2026-08-23 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0051_announcement_community_and_more'),
        ('emergencies', '0046_emergencyalert_media_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='backuprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'assigned', 'pending_manual'])), fields=('alert', 'target_department'), name='emerg_backup_one_active_unit'),
        ),
    ]
