# Generated by Django 5.2.17 on 2026-08-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0048_emergencyalert_location_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='psgc_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
