# Generated by Django 5.2.15 on 2026-07-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0004_concern_latitude_concern_location_accuracy_and_more'),
        ('emergencies', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencies.emergencyalert'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='concern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='concerns.concern'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('emergency_submitted', 'Emergency Submitted'), ('emergency_routed', 'Emergency Routed'), ('emergency_acknowledged', 'Emergency Acknowledged'), ('emergency_en_route', 'Emergency En Route'), ('emergency_arrived', 'Emergency Arrived'), ('emergency_resolved', 'Emergency Resolved'), ('emergency_cancelled', 'Emergency Cancelled'), ('witness_alert', 'Witness Alert')], max_length=32),
        ),
    ]
