# Generated by Django 5.2.15 on 2026-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_browserpushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='browserpushsubscription',
            new_name='notificatio_user_id_7a4b0b_idx',
            old_name='notificatio_user_id_7cb750_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('announcement', 'Announcement'), ('emergency_submitted', 'Emergency Submitted'), ('emergency_routed', 'Emergency Routed'), ('emergency_acknowledged', 'Emergency Acknowledged'), ('emergency_en_route', 'Emergency En Route'), ('emergency_arrived', 'Emergency Arrived'), ('emergency_resolved', 'Emergency Resolved'), ('emergency_cancelled', 'Emergency Cancelled'), ('witness_alert', 'Witness Alert')], max_length=32),
        ),
    ]
