# Generated by Django 5.2.15 on 2026-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificatio_user_id_7cb750_idx_notificatio_user_id_7a4b0b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('announcement', 'Announcement'), ('clarification_requested', 'Clarification Requested'), ('clarification_replied', 'Clarification Replied'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_approved', 'Appeal Approved'), ('appeal_denied', 'Appeal Denied'), ('emergency_submitted', 'Emergency Submitted'), ('emergency_routed', 'Emergency Routed'), ('emergency_acknowledged', 'Emergency Acknowledged'), ('emergency_en_route', 'Emergency En Route'), ('emergency_arrived', 'Emergency Arrived'), ('emergency_resolved', 'Emergency Resolved'), ('emergency_cancelled', 'Emergency Cancelled'), ('witness_alert', 'Witness Alert')], max_length=32),
        ),
    ]
