# Generated by Django 5.2.15 on 2026-07-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_event_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notifications_recipient_event_key_unique',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event_key',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
    ]
