# Generated by Django 5.2.15 on 2026-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_notification_notifications_recipient_event_key_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('announcement', 'Announcement'), ('clarification_requested', 'Clarification Requested'), ('clarification_replied', 'Clarification Replied'), ('appeal_submitted', 'Appeal Submitted'), ('appeal_approved', 'Appeal Approved'), ('appeal_denied', 'Appeal Denied'), ('concern_comment', 'Concern Comment'), ('concern_mention', 'Concern Mention'), ('chat_message', 'Chat Message'), ('emergency_submitted', 'Emergency Submitted'), ('emergency_routed', 'Emergency Routed'), ('emergency_acknowledged', 'Emergency Acknowledged'), ('emergency_en_route', 'Emergency En Route'), ('emergency_nearby', 'Emergency Nearby'), ('emergency_arrived', 'Emergency Arrived'), ('emergency_resolved', 'Emergency Resolved'), ('emergency_cancelled', 'Emergency Cancelled'), ('emergency_escalated', 'Emergency Escalated'), ('emergency_appeal_submitted', 'Emergency Appeal Submitted'), ('emergency_appeal_approved', 'Emergency Appeal Approved'), ('emergency_appeal_denied', 'Emergency Appeal Denied'), ('witness_alert', 'Witness Alert')], max_length=32),
        ),
    ]
