# Generated by Django 5.2.15 on 2026-08-22 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0049_concern_concern_status_queue'),
        ('emergencies', '0040_emergencycategory_visible_to_residents'),
        ('notifications', '0018_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_archived', 'is_read', 'created_at'], name='notif_recipient_inbox'),
        ),
    ]
