# Generated by Django 5.2.17 on 2026-08-23 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerns', '0051_announcement_community_and_more'),
        ('emergencies', '0041_backuprequest_community_emergencyassignmentroute_and_more'),
        ('notifications', '0019_notification_notif_recipient_inbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencies.community'),
        ),
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='concerns.department'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['community', 'department', 'created_at'], name='notif_comm_dept_time'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__gt', '')), fields=('recipient', 'event_key'), name='notif_recipient_event_uniq'),
        ),
    ]
