# Generated by Django 5.2.17 on 2026-09-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0023_nativepushdevice_per_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
